### ISSUE TITLE
kubernetes_pod_name label config example

### ISSUE THREAD

**Issue by marcin-kasinski** [kubernetes-sigs/prometheus-adapter#112]
Kubernetes v1.11.3
Adapter image: directxman12/k8s-prometheus-adapter-amd64 

Your prometheus adapter works fine with example config if there is pod label in my metric. I've checked it in my dev environment.

I can see my pod metics with command:

`kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/" | jq '.' | grep pod`

Problem is that my prometheus configuration is different.

In prometheus I have metric:

`MKWEB_exec_time_seconds_max{app="springbootweb",host="MYHOST",instance="10.244.0.19:7070",job="kubernetes-pods",kubernetes_pod_name="springbootweb-7c5998fdd-ktnw5",namespace="default",pod_template_hash="371554988",region="us-east-1"}`

Based on your config doc I've added additional rule to adapter config:

```

- seriesQuery: 'MKWEB_exec_time_seconds_max{namespace!="",kubernetes_pod_name!=""}'
  resources:
    overrides:
      kubernetes_namespace: {resource: "namespace"}
      kubernetes_pod_name: {resource: "pod"}
  name:
    matches: "^(.*)_total"
    as: "${1}_per_second"
  metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'

```

  With this configuration I can not see my metrics.
  
  Can you tell what is wrong with my configuration ?
