### ISSUE TITLE
Can I combine metrics in the config?

### ISSUE THREAD

**Issue by rrtaylor** [kubernetes-sigs/prometheus-adapter#116]
I would like to auto-scale my cluster by a formula of metrics provided by Prometheus. From the config walkthrough, I only see ways of aggregating metrics (and converting them into rates). Could you provide an example of creating a formula of multiple prometheus metrics into a single metric that the HPA can take?  

For example, I would like to scale to the point where my queue will be consumed in a minute, so I would like to set an hpa of the following formula metric to target a value of 60:
`avg(queue_length) / sum(rate(http_calls_total[5m]))`

My latest config setup to try to accomplish this is as follows:
``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: custom-metrics
data:
  config.yaml: |
    rules:
    - seriesQuery: '{namespace!="",__name__!~"^container_.*"}'
      seriesFilters: []
      resources:
        template: <<.Resource>>
      name:
        matches: ^(.*)
        as: "formula"
      metricsQuery: avg(queue_length) / sum(rate(http_calls_total[5m]))
```

With this, I'm able to see the metric on the custom.metrics api:

``` shell
$ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" | jq . | grep "pods"
      ...
      "name": "pods/http_calls_total",
      "name": "pods/queue_length",
      "name": "pods/formula",
```
But the the API shows an empty items list (where the metrics value would be) at `/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/*/formula`:

``` json
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/%2A/formula"
  },
  "items": []
}
```

**Comment by DirectXMan12** [comment]
>  Could you provide an example of creating a formula of multiple prometheus metrics into a single metric that the HPA can take?

This was supposed to help, but if it's not clear, please let me know: https://github.com/DirectXMan12/k8s-prometheus-adapter#my-query-contains-multiple-metrics-how-do-i-make-that-work

Basically, the gist is that you need one metric to act as the discovery metric, and the resulting query *must* have labels matching the resources provided in your resource template, and there should be one entry per object.

I suspect the issue is that you don't have any matching labels, but that's just a hunch.

**Comment by richardbrks** [comment]
Thank you. I was able to get it working, but I had to change the `resources` value to use the template instead:

```yaml
      resources:
        template: <<.Resource>>
```

I also tried replacing `node` for `pod`, `service`, and `deployment` , but using any of these made it so the metric never appeared in `/apis/custom.metrics.k8s.io/v1beta1`.

**Comment by sylr** [comment]
I've a pretty similar case but a little bit more twisted.

I'd like to combine two absolutely unrelated metrics and compute a ratio out off it:

- `sum(rabbitmq_queue_messages{queue})`: current number of message in a given queue
- `sum(kube_deployment_status_replicas{namespace,deployment})`: current number of ready pods for a given deployment

the query looks like this (<<.xxxx>> are currently hardcoded.):

```
sum(rabbitmq_queue_messages{queue=~"<<.queue>>"}) 
/
ignoring (namespace, deployment) group_right sum(kube_deployment_status_replicas{namespace="<<.namespace>>",deployment="<<.deployment>>"}) by (namespace,deployment) 
```
This computes the ratio waiting messages per ready pods for a given deployment.

My question here would be, **would it be possible to dynamically take the value of <<.queue>> out of the deployment labels** ?

**Comment by elblivion** [comment]
I stumbled upon this issue and have a simpler but similar use case as @sylr. I'd like to use HPA on an AMQP consumer based on the `rabbitmq_queue_messages` metric, on a given label. Currently I'm struggling with this because I can't see any way to generate metrics based on label values, the metrics can be renamed but they must map one-to-one with metric series - is there any way to create metrics names for one Service/Pod based on another pod's labels?

Our RabbitMQ cluster has a metric rabbitmq_queue_messages, each consumer creates their own queue. Ideally we should be able to scale the deployment based on its own queue name, but using a metric from the RabbitMQ cluster.

**Comment by DirectXMan12** [comment]
> is there any way to create metrics names for one Service/Pod based on another pod's labels?

Not really, at the moment.  This may be a usecase for external metrics, when support for that lands.

**Comment by VinayVanama** [comment]
@richardbrks @DirectXMan12 How to write our own custom rule ? what I'm trying to achieve is I have a deployment and I need it to be scaled based on total_number_http_requests, I'm a way confused to achieve this ! Should I write my own rules in prometheus adapter ?

**Comment by sebarys** [comment]
@Sanjanare Let's assume you have `rabbitmq_queue_messages` metric that report queue size and application called `orders` that consume messages from queue called `orders-queue`. Application is deployed in `api` namespace and exposed by `orders` service.
Below simplified plan how we can start scale this app based on `orders-queue` queue size:

1. `rabbitmq_queue_messages` metric doesn't contain information about namespace and service connected with your application deployment,so you need add somehow required labels. It can be done by Prometheus recording rule ( https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/ )

So we want create new metric `enriched_rabbitmq_queue_messages`  based on `rabbitmq_queue_messages` that will have for queue `orders-queue` two additional labels:
- `namespace: api`
- `service: orders`

Manifest with definition of such recording rule:
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: api-rules
    prometheus: kube-prometheus
  name: api.queues
  namespace: api
spec:
  groups:
  - name: queues
    rules:
    - record: enriched_rabbitmq_queue_messages
      expr: rabbitmq_queue_messages{queue="orders-queue"}
      labels:
        namespace: api
        service: orders
```

2. As we now have metric that can be used to create custom metrics rule, lets try to do it:
```
   - seriesQuery: 'enriched_rabbitmq_queue_messages{namespace!="",service!=""}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          service: {resource: "service"}
      name:
        matches: "^(.*)"
        as: "${1}"
      metricsQuery: 'enriched_rabbitmq_queue_messages{<<.LabelMatchers>>}'
```

3. If custom metrics rule is now applied to your `prometheus-adapter` we can use it to scale `orders` application based on `orders-queue` queue size: 
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: orders
  namespace: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Object
      object:
        target:
          kind: Service
          name: orders
        metricName: enriched_rabbitmq_queue_messages
        targetValue: 1
```

@cdaguerre thanks for your solution, it saved my day!
