### ISSUE TITLE
[feature] Ability to use label data to configure metric/association names

### ISSUE THREAD

**Issue by rodolfo-picoreti** [kubernetes-sigs/prometheus-adapter#138]
I am currently trying to expose queue metrics from RabbitMQ to auto-scale some deployments. I am facing some problems while trying to associate the metric with the corresponding kubernetes resource. To do so, I would need to be able to read and "transform" label information in order to generate the corresponding resource name and metric name.

Metric example:
```
rabbitmq_queue_messages_published_total{durable="false",endpoint="http",instance="10.42.0.4:8080",job="rabbitmq-exporter",namespace="monitoring",pod="rabbitmq-exporter-868bc6cd98-bdhxj",policy="default",queue="CameraGateway.0.SetConfig",service="rabbitmq-exporter",vhost="/"}
```
I would like to associate this metric with a deployment or service named something like "**_CameraGateway-0_**". Also I would like the metric name to be something like "_**SetConfig_msgs_per_second**_".

To solve this, I am currently associating the metric with a service resource with the same name as the queue. The resouce does not exist, but apparently that is not a problem. By querying `http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/services/CameraGateway.0.SetConfig/rabbitmq_msgs_per_second` I get the expected metric value.

```yaml
    rules:
    - seriesQuery: 'rabbitmq_queue_messages_published_total{namespace!="",queue!=""}'
      seriesFilters: []
      resources:
        overrides:
          namespace:
            resource: namespace
          queue:
            resource: service 
      name:
        matches: ""
        as: "rabbitmq_msgs_per_second"
      metricsQuery: rate(rabbitmq_queue_messages_published_total [1m]) / rabbitmq_queue_consumers  
```

This issue is more or less similar to #137.

**Comment by tmatias** [comment]
> To solve this, I am currently associating the metric with a service resource with the same name as the queue

I guess you can solve that in prometheus, with a relabel:

```yaml
- source_labels: [queue]
  target_label: deployment
  regex: ^(.*\.\d+)\..*$
  replacement: $1
```

That way, a queue named `CameraGateway.0.SetConfig`, will get you a label `deployment=CameraGateway.0`, but a queue named `SomeOtherThing.1.SomeOtherAction` will end up as `deployment=SomeOtherThing.1`.

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cmetric_relabel_configs%3E
