### ISSUE TITLE
Unable to fetch metrics

### ISSUE THREAD

**Issue by danisabad** [kubernetes-sigs/prometheus-adapter#150]
Hello.

I have a metric in Prometheus:

    nginx_ingress_controller_requests{controller_class="nginx",
      controller_namespace="default",
      controller_pod="my-nginx-nginx-ingress-controller-5b858c69c9-z4sns",
      endpoint="metrics",
      exported_namespace="default",
      ingress="hello-world-ingress",
      instance="10.244.0.22:10254",
      job="my-nginx-nginx-ingress-controller-metrics",
      namespace="default",
      pod="my-nginx-nginx-ingress-controller-5b858c69c9-z4sns",
      service="my-nginx-nginx-ingress-controller-metrics",
      status="200"}

Created an adapter rule:

    - seriesQuery: 'nginx_ingress_controller_requests{status="200"}'
      resources:
        overrides:
          ingress: {resource: "ingress"}
      name:
        matches: "^(.*)"
        as: "${1}_per_second"
      metricsQuery: 'rate(<<.Series>>{<<.LabelMatchers>>}[5m]) by (<<.GroupBy>>)'

And I even can see it appearing in APIs:

    $ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" | jq .
    {
      "kind": "APIResourceList",
      "apiVersion": "v1",
      "groupVersion": "custom.metrics.k8s.io/v1beta1",
      "resources": [
        {
          "name": "ingresses.extensions/nginx_ingress_controller_requests_per_second",
          "singularName": "",
          "namespaced": false,
          "kind": "MetricValueList",
          "verbs": [
            "get"
          ]
        }
      ]
    }

But I (and HPA too) can't fetch metrics from API

    $ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespace/default/ingresses.extensions/*/nginx_ingress_controller_requests_per_second" | jq . 
    Error from server (NotFound): the server could not find the requested resource
    $ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespace/default/ingresses.extensions/hello-world-ingress/nginx_ingress_controller_requests_per_second" | jq . 
    Error from server (NotFound): the server could not find the requested resource
    $ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/ingresses.extensions/hello-world-ingress/nginx_ingress_controller_requests_per_second" | jq . 
    Error from server (InternalError): Internal error occurred: unable to fetch metrics

Maybe I just don't understand something. Because when I enable default metrics in the adapter, I can see nginx_ingress_controller_requests metrics and able to couple it with HPA.

P.S. Sorry, I didn't find any usergroup or main list, so I'm writing here.

**Comment by sepulworld** [comment]
I have a similar issue except with istio_request metrics. Everything looks good until I try to pull metrics from API, they don't exist.

```
rules:
  custom:
  - seriesQuery: '{__name__=~"^istio_request_.*"}'
    resources:
      template: <<.Resource>>
    name:
      matches: ^istio_request_(.*)$
      as: ""
    metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
```

**Comment by DirectXMan12** [comment]
You'll want a resource for namespace, too.  That's probably the issue.  If you have a namespaced resource, you need to have mappings for both namespace and the resource (and ingress is namespaced).

**Comment by bzon** [comment]
@danisabad, were you able to solve this problem?

@DirectXMan12, 

> You'll want a resource for namespace, too. That's probably the issue. If you have a namespaced resource, you need to have mappings for both namespace and the resource (and ingress is namespaced).

How about this configuration? See the mapping. Nginx prometheus metrics has **exported_namespace**, **exported_service** and **ingress** for mapping.

```yaml
    - seriesQuery: '{controller_class="nginx",ingress!="",exported_namespace!="",exported_service!=""}'
      seriesFilters:
        - is: ^nginx_ingress_controller_request_duration_seconds_bucket$
      resources:
        overrides:
          ingress:
            resource: ingress
          exported_namespace:
            resource: namespace
          exported_service:
            resource: service
      name:
        as: nginx_ingress_controller_request_duration_seconds_rate_99_pct
      metricsQuery: 'histogram_quantile(0.99, sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (le, ingress))'
```

This is the example nginx ingress controller prometheus metrics:

```txt
nginx_ingress_controller_request_duration_seconds_bucket{controller_class="nginx",controller_namespace="nginx-ingress",controller_pod="ingress-controller-nginx-ingress-controller-64fd4f454d-hkh5c",endpoint="10254",exported_namespace="production",exported_service="foo-api",host="t.fstrk.net",ingress="foo-api-ingress",instance="10.8.0.80:10254",job="ingress-controller-nginx-ingress-controller",le="0.5",method="GET",namespace="nginx-ingress",path="/api",pod="ingress-controller-nginx-ingress-controller-64fd4f454d-hkh5c",service="ingress-controller-nginx-ingress-controller",status="503"}

nginx_ingress_controller_request_duration_seconds_bucket{controller_class="nginx",controller_namespace="nginx-ingress",controller_pod="ingress-controller-nginx-ingress-controller-64fd4f454d-hkh5c",endpoint="10254",exported_namespace="production",exported_service="foo-api",host="t.fstrk.net",ingress="foo-api-ingress",instance="10.8.0.80:10254",job="ingress-controller-nginx-ingress-controller",le="0.5",method="GET",namespace="nginx-ingress",path="/api",pod="ingress-controller-nginx-ingress-controller-64fd4f454d-hkh5c",service="ingress-controller-nginx-ingress-controller",status="499"}
```

Testing the metrics:

```bash
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/foo/services/production/nginx_ingress_controller_request_duration_seconds_rate_99_pct" | jq '.'
```

gives nothing in the metrics:

```json
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/production/services/%2A/nginx_ingress_controller_request_duration_seconds_rate_99_pct"
  },
  "items": []
}
```

I will appreciate if you can enlighten us what we have been doing wrong. Thank you!

**Comment by mohammadasim** [comment]
Any update on this issue. I am facing exactly the same problem.
`kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 | jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "services/service_response_time",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}`
But when I run the following command, I get error resource not found. 
`kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespace/default/service/*/service_response_time | jq
Error from server (NotFound): the server could not find the requested resource`

**Comment by prageethw** [comment]
I'm in similar situation too, I can see adaptor successfully run query against Prometheus server but not being able to return in custom metrics.
sql```
 
 GET http://prometheus.istio-system.svc:9090/api/v1/query?query=sum%28rate%28istio_requests_total%7Bdestination_workload_namespace%3D%22go-demo-7%22%2Cdestination_service_name%3D%22go-demo-7%22%2Creporter%3D%22destination%22%7D%5B1m%5D%29%29%2Fcount%28count%28container_memory_usage_bytes%7Bnamespace%3D%22go-demo-7%22%2Cpod_name%3D~%22go-demo-7-primary.%2A%22%7D%29+by+%28pod_name%29%29&time=1580466131.092 200 OK

prometheus-adapter-6f6f9464bf-zh7l6 prometheus-adapter I0131 10:22:11.094411       1 api.go:93] Response Body: {"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1580466131.092,"0.3037037037037037"]}]}}

prometheus-adapter-6f6f9464bf-zh7l6 prometheus-adapter E0131 10:22:11.094609       1 provider.go:164] None of the results returned by when fetching metric services/tps_service_requests(namespaced) for "go-demo-7/go-demo-7" matched the resource name
prometheus-adapter-6f6f9464bf-zh7l6 prometheus-adapter I0131 10:22:11.094774       1 wrap.go:42] 

GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/go-demo-7/services/go-demo-7/tps_service_requests: (5.773393ms) 404 [[kube-controller-manager/v1.15.9 (linux/amd64) kubernetes/2e808b7/system:serviceaccount:kube-system:horizontal-pod-autoscaler] 172.20.33.13:42930]

```
my adoptor config is
sh```
  - seriesQuery: 'istio_requests_total'
    resources:
      overrides:
        destination_service_name: {resource: "service"}
        destination_workload_namespace: {resource: "namespace"} 
    name:
      as: "tps_service_requests"
    metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>,reporter="destination"}[1m]))/count(count(container_memory_usage_bytes{namespace="go-demo-7",pod_name=~"go-demo-7-primary.*"}) by (pod_name))'
```
my hpa

yaml```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: go-demo-7
  namespace: go-demo-7
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-demo-7-primary
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: tps_service_requests
      describedObject:
        apiVersion: v1 #make sure you check the api version on the targeted resource using get command.
        kind: Service
        name: go-demo-7
      target:
        type: Value
        value: 50m
```

**Comment by BenCoughlan15** [comment]
getting the same issue here, any chance of getting some docs on how to install this? using namespaces should hardly be treated as an edge case?

**Comment by nisan270390** [comment]
Faced with the same issue, I'm trying to set custom metric
```
- metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,reporter="destination"}[1m]))
      name:
        as: http_requests
      resources:
        overrides:
          destination_service_name:
            resource: service
          destination_workload_namespace:
            resource: namespace
      seriesQuery: istio_requests_total
```


I get the following log:
```
I0708 14:35:28.203020       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1: (283.178µs) 200 [Go-http-client/2.0 10.0.46.89:27608]
I0708 14:35:28.203048       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1: (235.767µs) 200 [Go-http-client/2.0 10.0.46.89:27608]
I0708 14:35:28.203020       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1: (242.222µs) 200 [Go-http-client/2.0 10.0.46.89:27608]
I0708 14:35:28.203025       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1: (208.974µs) 200 [Go-http-client/2.0 10.0.46.89:27608]
I0708 14:35:28.203028       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1: (273.148µs) 200 [Go-http-client/2.0 10.0.46.89:27608]
I0708 14:35:28.631951       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/devops/services/k8s-workshop-service/http_requests: (1.992389ms) 404 [kube-controller-manager/v1.15.11 (linux/amd64) kubernetes/d94a81c/system:serviceaccount:kube-system:horizontal-pod-autoscaler 10.0.34.139:59492]
```

Does anyone come across and know how to solve it?
