### ISSUE TITLE
Prometheus adaptor fails to load custom metrics with invalid metric

### ISSUE THREAD

**Issue by gogineni99** [kubernetes-sigs/prometheus-adapter#225]
**What happened?**
Used a new rule in promethues adaptor-config ConfigMap to use a custom metric in HPA via CustomMetric API.Works fine when the metric used in 'seriesQuery' is valid. If the metric in 'serierQuery' is invalid (metric became invalid when the pods go down or the metric does not exist any longer), all other valid metrics/series fail to load.

```
E0722 15:00:58.683001       1 provider.go:206] unable to update list of all metrics: no metrics retrieved for query 
```

Other than the rule/seriesQuery with invalid metric, the rest should load and should be available for custom metric API

**Steps to reproduce**:
Installed prometheus-operator and Custom metric api from 
Deploy the manifest from https://github.com/coreos/kube-prometheus/tree/master/experimental/custom-metrics-api
```
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 
```
- Will give you results of custom metrics, which looks correct

Add a new rule with a invalid metric name like below. 

    ```
- seriesQuery: 'invalid_metric_name{namespace!="",pod!=""}'
      seriesFilters: []
      resources:
        overrides:
            namespace:
                resource: namespace
            pod:
                resource: pod
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)' 
```     

```
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 
```
- Will give you empty results.

* Prometheus Adapter Logs:

```
E0722 15:39:50.045412       1 provider.go:206] unable to update list of all metrics: no metrics retrieved for query "invalid_metric_name{namespace!=\"\",pod!=\"\"}"
```
