### ISSUE TITLE
SQS number of messages in queue

### ISSUE THREAD

**Issue by johnjeffers** [kubernetes-sigs/prometheus-adapter#232]
Has anyone had any luck getting this to work with SQS metrics? I've got the prometheus-cloudwatch-exporter sending cloudwatch metrics to prometheus, and have confirmed those metrics are in prometheus (see attached screen shot).

<img width="1388" alt="Screen Shot 2019-08-19 at 4 06 43 PM" src="https://user-images.githubusercontent.com/11821214/63303238-767b7580-c29c-11e9-9a0a-0dd1afbb51a2.png">

I can't for the life of me figure out how to write the config for the prometheus-adapter to pull those metrics out of prometheus and expose them to HPA in the metrics API. I have read the docs over and over and still don't follow how to write the rules to do this. My latest attempt looks like this:

```
  custom:
    - seriesQuery: 'aws_sqs_approximate_number_of_messages_visible_sum{queue_name="MySqsQueueName"}'
      resources:
        overrides:
          sqsdepth: {group: "apps", resource: "deployment"}
      name:
        as: "sqs_depth_MySqsQueueName"
      metricsQuery: 'aws_sqs_approximate_number_of_messages_visible_sum{queue_name="MySqsQueueName"}'
```

Nor do I understand, once I have done so, what the path in the custom metrics API endpoint is supposed to look like. With the above I get this:

```
» kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/ | jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": []
}
```

So it looks like nothing was created? Or maybe it was and it's just not obvious? I can't tell. I feel totally frustrated and lost trying to figure this out.

All I want to do is expose the number of messages in an SQS queue to HPA so a deployment can scale based on the number of messages in the queue. I've been struggling with this for days. If someone is able to explain this to me, I will happily push a PR to the docs to try to make it clearer for others in the future.

**Comment by hugobcar** [comment]
Hi @johnjeffers.

We have developed our tool that collects SQS metrics to replace CloudWatch Exporter. We developed the tool because CloudWatch Exporter takes at least 5 minutes to collect metrics and this is too late for us.

We will put more information in the documentation and send you the repo if you are interested.

**Comment by mthssdrbrg** [comment]
As @hugobcar points out (I think at least, unless I'm misunderstanding what they mean), there's usually around a 5 minute delay for metrics scraped from CloudWatch, so we typically add `offset 5m` to our queries. Mind that we haven't actually tried to use any metrics from CloudWatch for scaling, so YMMV.

Just thought I'd throw it out there.

**Comment by mthssdrbrg** [comment]
Hold on, reading through some other issues, maybe this should be handled through the `--metrics-max-age` flag (that's by default set to 20 minutes), but there might still be some issues with CloudWatch lagging behind (really thinking out loud here, so let me know if I'm wrong!).

**Comment by hugobcar** [comment]
@johnjeffers @mthssdrbrg take a look at this tool https://github.com/hugobcar/tiamat

**Comment by johnjeffers** [comment]
@hugobcar thank you for the suggestion, but that will cover just one specific use case, and I want to get the prometheus-adapter working so I can use HPA with any metric in prometheus. I understand that you needed something faster than 5 minutes, but for my needs, that delay is acceptable.

My colleague and I have been working on this, and think we have a slightly better understanding of how to write the `seriesQuery` and `metricsQuery`, but still can't get it working. One thing we're definitely not clear on is how to format the `resources` when you're dealing with an external metric that doesn't fit into a kube namespace/service/pod. The current attempt looks like this:

```
    externalRules:
    - metricsQuery: max_over_time(<<.Series>>{<<.LabelMatchers>>}[20m])
      name:
        as: sqs_depth
        matches: ""
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
          service:
            resource: service
      seriesQuery: aws_sqs_approximate_number_of_messages_visible_maximum{queue_name!=""}
```

We've changed our approach and are trying to use it as an external metric (since it is that) rather than a custom metric. Still can't get it to register, though.

```
# kubectl get --raw '/apis/external.metrics.k8s.io/v1beta1/' | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": []
}
```

Still do not know what we're doing wrong.
