### ISSUE TITLE
Metrics query does not work as expected when aggregation is used

### ISSUE THREAD

**Issue by mazzy89** [kubernetes-sigs/prometheus-adapter#239]
I'm using the following custom metric config:

```yaml
- seriesQuery: '{__name__="sidekiq_jobs_waiting_count", job=~".*sidekiq", queue!="notifications"}'
  resources:
    overrides:
       namespace: { resource: "namespace" }
       service: { resource: "services" }
   name:
     as: "sidekiq_jobs_enqueued"
   metricsQuery: "sum(max(<<.Series>>{<<.LabelMatchers>>}) by (queue))"
```

I'm sure that the _discovery_ process works because using `-v=6` I got `200` from Prometheus series API.

What it does not work as expected as suppose is `metricsQuery`.

When indeed I get:

```
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/%2A/metrics/sidekiq_jobs_enqueued"
  },
  "items": []
}
```

I suspect that the aggregation `by (queue)` breaks the thing not giving back any results and the reason is that I don't have the label `queue` available.

How to proceed from here?

**Comment by mazzy89** [comment]
I've changed the query in:

```yaml
- seriesQuery: '{__name__="sidekiq_jobs_waiting_count"}'
  resources:
    overrides:
       namespace: { resource: "namespace" }
       service: { resource: "services" }
   name:
   as: "sidekiq_jobs_enqueued"
   metricsQuery: "sum(max(sidekiq_jobs_waiting_count{job=~".*sidekiq", queue!="notifications", <<.LabelMatchers>>}) by (queue))"
```

I've noticed that when I run 

```
➜ k get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/metrics/sidekiq_jobs_enqueued" | jq .
```

I get this in thee prometheus-adapter logs

```
GET http://kube-prometheus-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/query?query=sum%28max%28sidekiq_jobs_waiting_count%7Bjob%3D~%22.%2Asidekiq%22%2C+queue%21~%22notifications%7Cmigrations%22%2C+namespace%3D%22default%22%7D%29+by+%28queue%29%29&time=1571308159.456 200 OK
```

but the result of th command is 
```
Error from server (NotFound): the server could not find the metric sidekiq_jobs_enqueued for namespaces default
```
