### ISSUE TITLE
Goroutine issue when fetch the query from external.api 

### ISSUE THREAD

**Issue by WoodProgrammer** [kubernetes-sigs/prometheus-adapter#242]
Hello everyone,
I have implemented and registered external api to the k8s environment  but I have some issues when fetch the metrics . 

That is rule for external api metrics : 

```
  - seriesQuery: 'http_requests_total{namespace!="",pod!=""}'
    resources:
      overrides:
        kubernetes_namespace: {resource: "namespace"}
        kubernetes_pod_name: {resource: "pod"}
    name:
      matches: "^(.*)_total"
      as: "${1}"
```
When check the kubernetes external api metrics , resources values is not null that looks fine but , 

```
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "http_requests",
      "singularName": "",
      "namespaced": true,
      "kind": "ExternalMetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```

After all those things, when I want check the value of `http_requests` metric kubernetes returning this error ;

`Error from server (InternalError): Internal error occurred: unable to fetch metrics`

I have checked this issue from `prometheus-adapter` pod these are error logs related with this query ; 

 ```
E1005 01:21:26.387384       1 provider.go:47] unable to generate a query for the metric: empty query produced by metrics query template
I1005 01:21:26.387594       1 wrap.go:42] GET /apis/external.metrics.k8s.io/v1beta1/namespaces/default/http_requests: (504.956µs) 500
goroutine 1909 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc420374930, 0x1f4)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xd2
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc420374930, 0x1f4)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc42105b2a0, 0x1f4)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:192 +0xac
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc42107f920, 0x1f4)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:307 +0x45
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x1791e20, 0x10, 0x7f340078e6c8, 0xc4204ec580, 0x190fd20, 0xc420e8db88, 0xc421081600, 0x1f4, 0x18f9920, 0xc420039320)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:95 +0x8d

....
....
....

``` 

But I have parsed this error message : `unable to generate a query for the metric: empty query produced by metrics query template` 

## Kubernetes Version : v1.13.11

What is the reason of this issue ? 

Help please

**Comment by john-delivuk** [comment]
Hey @WoodProgrammer  It looks like a config issue with my morning eyes.
```
  - seriesQuery: 'http_requests_total{namespace!="",pod!=""}'
    resources:
      overrides:
        kubernetes_namespace: {resource: "namespace"}
        kubernetes_pod_name: {resource: "pod"}
    name:
      matches: "^(.*)_total"
      as: "${1}"
```
So here you have `namespace` and `pod` hardcoded into your config. Then you're mapping the kubernetes value for namespace to `kubernetes_namespace` in your prom query as well has `kubernetes_pod_name` and pod value. I might suggest something like this. 
```
  - seriesQuery: 'http_requests_total{pod_name!="POD", namespace!=""}'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod_name: {resource: "pod"}
    name:
      matches: "^(.*)_total"
      as: "${1}"
```

Now this makes the assumption you're using `pod_name` which is what's most common and not `pod`. If you are then switch those values out to `pod` in place of `pod_name`.
