### ISSUE TITLE
Can we do the division in the metricsQuery?

### ISSUE THREAD

**Issue by mJace** [kubernetes-sigs/prometheus-adapter#251]
I wonder if I can do the division in the metricsQuery.
My flask pod exposes some latency related metrics. 
And I use grafana to get the metrics to show the request latency by
```
rate(app_request_latency_seconds_sum{pod=~"$pod"}[$interval]) 
/ 
rate(app_request_latency_seconds_count{pod=~"$pod"}[$interval])
```

I am able to get one metric by adding this to configMap of prometheus-adatper.
```
- seriesQuery: 'app_request_latency_seconds_sum{http_status=\"404\",pod!=\"\"}'
      resources:
        template: <<.Resource>>
      name:
        matches: ^(.*)_count_total$
        as: "${1}_per_minute"
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container_name!=\"POD\"}[1m])) by (<<.GroupBy>>)
```

How to get two metric and do the division in the metricsQuery?
Or I have to finish all the calculation be before prometheus-adatper query it?
