### ISSUE TITLE
custom metrics not work(http2: stream closed)

### ISSUE THREAD

**Issue by tallongsun** [kubernetes-sigs/prometheus-adapter#264]
I'm running the adapter with the following command .
```
git clone https://github.com/coreos/kube-prometheus.git
cd kube-prometheus/
kubectl create -f manifests/setup
kubectl create -f manifests/ 
cd experimental/custom-metrics-api
sh deploy.sh
kubectl apply -f sample-app.yaml
```

when i try to run `kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1"`, i got the error `Error from server (ServiceUnavailable): the server is currently unable to handle the request`
 
and i check the adapter log, i found the following error.
> apiserver was unable to write a JSON response: http2: stream closed
> apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}

what should i do to make the metrics api start up?
My k8s version is 
> Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tallongsun** [comment]
btw, i can retrieve http_requests_total metric from prometheus directly , but can't retrieve from prometheus-adapter(custom metric server)

**Comment by nvanheuverzwijn** [comment]
In my case, the server works well but I get those same errors. Not sure what it is related to ?

The code where the error originate have these comments

                // Log errors that were not converted to an error status
                // by REST storage - these typically indicate programmer
                // error by not using pkg/api/errors, or unexpected failure
                // cases.

Maybe prometheus-adapter does not handle correctly when the http2 stream closed and output this error. I have no idea if we should we worried or not.

**Comment by GMartinez-Sisti** [comment]
Same here, all is working as it should, but those errors are still being thrown.

**Comment by nvanheuverzwijn** [comment]
I noticed that when you reduce/remove the numbers of custom metrics, it removes the error.

Could this be caused by the overwhelming number of custom metrics provided by the adapter ? The default metrics in the helm release looks like this :
```
    - seriesQuery: '{__name__=~"^container_.*",container!="POD",namespace!="",pod!=""}'
      seriesFilters: []
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: ^container_(.*)_seconds_total$
        as: ""
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container!="POD"}[5m]))
        by (<<.GroupBy>>)
    - seriesQuery: '{__name__=~"^container_.*",container!="POD",namespace!="",pod!=""}'
      seriesFilters:
      - isNot: ^container_.*_seconds_total$
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: ^container_(.*)_total$
        as: ""
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container!="POD"}[5m]))
        by (<<.GroupBy>>)
    - seriesQuery: '{__name__=~"^container_.*",container!="POD",namespace!="",pod!=""}'
      seriesFilters:
      - isNot: ^container_.*_total$
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: ^container_(.*)$
        as: ""
      metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>,container!="POD"}) by (<<.GroupBy>>)
    - seriesQuery: '{namespace!="",__name__!~"^container_.*"}'
      seriesFilters:
      - isNot: .*_total$
      resources:
        template: <<.Resource>>
      name:
        matches: ""
        as: ""
      metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
    - seriesQuery: '{namespace!="",__name__!~"^container_.*"}'
      seriesFilters:
      - isNot: .*_seconds_total
      resources:
        template: <<.Resource>>
      name:
        matches: ^(.*)_total$
        as: ""
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m])) by (<<.GroupBy>>)
    - seriesQuery: '{namespace!="",__name__!~"^container_.*"}'
      seriesFilters: []
      resources:
        template: <<.Resource>>
      name:
        matches: ^(.*)_seconds_total$
        as: ""
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m])) by (<<.GroupBy>>)
```

Those default rules seems to be very intensive. It fetches almost all metrics from prometheus and execute sum/rate on all of them to provide custom metrics. Maybe it shouldn't be the default ? Why this specific configuration the default ?

@tallongsun Make sure the api is correctly being served by kubernetes. You can check it out with `kubectl get apiservices.apiregistration.k8s.io | grep metrics.k8s.io`. You should see an output like so `v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        96d`. You can then check if your service actually runs with `kubectl -n monitoring get svc prometheus-adapter` (make sure you change the namespace and the service name to correspond to what you retrieved with `kubectl get apiservices`).
