### ISSUE TITLE
Issue with v1beta1.metrics.k8s.io and calico(?)

### ISSUE THREAD

**Issue by matandomuertos** [kubernetes-sigs/prometheus-adapter#268]
Hello, I was fighting with this issue for the last few days and i dont find any solution for the moment.

Basically I want to install prometheus-adapter in eks running k8s v1.14.9.

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

The problem is basically that `v1beta1.metrics.k8s.io` can't connect to prometheus-adapter.

I tried two ways:

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus-adapter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: prometheus-adapter
    spec:
      #hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/services: services
      tolerations:
      - key: workload
        operator: Equal
        value: services
        effect: NoSchedule
      containers:
      - args:
        - --cert-dir=/var/run/serving-cert
        - --config=/etc/adapter/config.yaml
        - --logtostderr=true
        - --metrics-relist-interval=1m
        - --prometheus-url=http://prometheus-k8s.monitoring.svc:9090/
        - --secure-port=6443
        image: quay.io/coreos/k8s-prometheus-adapter-amd64:v0.4.1
        name: prometheus-adapter
        ports:
        - containerPort: 6443
        volumeMounts:
        - mountPath: /tmp
          name: tmpfs
          readOnly: false
        - mountPath: /var/run/serving-cert
          name: volume-serving-cert
          readOnly: false
        - mountPath: /etc/adapter
          name: config
          readOnly: false
      serviceAccountName: prometheus-adapter
      volumes:
      - emptyDir: {}
        name: tmpfs
      - emptyDir: {}
        name: volume-serving-cert
      - configMap:
          name: adapter-config
        name: config
```

I get this error:
```
Name:         v1beta1.metrics.k8s.io
Namespace:    
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"apiregistration.k8s.io/v1","kind":"APIService","metadata":{"annotations":{},"name":"v1beta1.metrics.k8s.io"},"spec":{"group...
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2020-01-31T08:16:56Z
  Resource Version:    6552785
  Self Link:           /apis/apiregistration.k8s.io/v1/apiservices/v1beta1.metrics.k8s.io
  UID:                 xxx-xxx-xxx-xxx-xxxx
Spec:
  Group:                     metrics.k8s.io
  Group Priority Minimum:    100
  Insecure Skip TLS Verify:  true
  Service:
    Name:            prometheus-adapter
    Namespace:       monitoring
  Version:           v1beta1
  Version Priority:  100
Status:
  Conditions:
    Last Transition Time:  2020-01-31T08:16:56Z
    Message:               no response from https://xx.xx.xx.xx:6443: Get https://xx.xx.xx.xx:6443: Address is not allowed
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>
```
I thought that the problem was some security group, i was playing a lot with them till even set to the control plane and node allow all traffic and still i get the same problem.

So I read that metrics has some problems with calico so i thought that was more or les the same, I set `hostNetwork: true` to prometheus-adapter deployment but i get another problem:

v1beta1.metrics.k8s.io seems ok:
```
Name:         v1beta1.metrics.k8s.io
Namespace:    
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"apiregistration.k8s.io/v1","kind":"APIService","metadata":{"annotations":{},"name":"v1beta1.metrics.k8s.io"},"spec":{"group...
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2020-01-31T08:29:08Z
  Resource Version:    6554748
  Self Link:           /apis/apiregistration.k8s.io/v1/apiservices/v1beta1.metrics.k8s.io
  UID:                 bfbebbc6-4403-11ea-a2e3-0a5f66f81db0
Spec:
  Group:                     metrics.k8s.io
  Group Priority Minimum:    100
  Insecure Skip TLS Verify:  true
  Service:
    Name:            prometheus-adapter
    Namespace:       monitoring
  Version:           v1beta1
  Version Priority:  100
Status:
  Conditions:
    Last Transition Time:  2020-01-31T08:29:10Z
    Message:               all checks passed
    Reason:                Passed
    Status:                True
    Type:                  Available
Events:                    <none>
```

but kubectl top doesnt work:
```
kubectl top node
Error from server: Error while fetching node metrics for selector : unable to fetch node CPU metrics: unable to execute query: Get http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum%281+-+rate%28node_cpu_seconds_total%7Bmode%3D%22idle%22%7D%5B1m%5D%29+%2A+on%28namespace%2C+pod%29+group_left%28node%29+node_namespace_pod%3Akube_pod_info%3A%7Bnode%3D~%22ip-10-xx-xx-xx.xx-central-1.compute.internal%7Cip-10-xx-xx-xx.xx-central-1.compute.internal%22%7D%29+by+%28node%29&time=1580459397.67: dial tcp: lookup prometheus-k8s.monitoring.svc on 10.xx.xx.xx:53: no such host
```

Again I tested the security groups and still nothing.

The last test was change `- --prometheus-url=http://prometheus-k8s.monitoring.svc:9090/` to the external url of prometheus and the problem was with TLS but has sense because prometheus is behind a load balancer which redirect to https and the idea is go internally, not externally.

I have exactly the same configuration (without hostNetwork) in another eks cluster with the same version but not running calico and works perfect. 

Do you have some idea about this?

Thanks!

**Comment by janvdvegt** [comment]
Did you end up solving this issue? I have the same problem

**Comment by Drupi** [comment]
any updates regarding this one ?

**Comment by TamasSzigeti** [comment]
Same issue here…

**Comment by TamasSzigeti** [comment]
The helm chart – and the config above – is missing the correct dnsPolicy. This is how I solved it:


```
helm install metrics prometheus-community/prometheus-adapter \
    --values values.prometheus-adapter.yaml \
    --namespace monitoring
kubectl patch deployment metrics-prometheus-adapter \
    --namespace=monitoring \
    --patch "$(cat hostnetwork.patch.yaml)"
``` 

And the patch is:
```
spec:
    template:
        spec:
            dnsPolicy: ClusterFirstWithHostNet
```

`hostNetwork: true` is already set by the chart correctly.
