### ISSUE TITLE
HPA based on Object AverageValue metric doesn't work as expected

### ISSUE THREAD

**Issue by tallongsun** [kubernetes-sigs/prometheus-adapter#283]
I created a hpa as below, i expect the sample-app could be scaled based on my gateway-service metric, For example,
>   gateway tps is 0-5, sample-app replica is 1
>   gateway tps is 5-10, sample-app replica is 2
>   gateway tps is 10-15, sample-app replica is 3
>   gateway tps is 15-20, sample-app replica is 4
>   gateway tps is 20, sample-app replica is 5

```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: sample-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Object
    object:
     metric:
       name: http_requests
     describedObject:
       apiVersion: v1
       kind: Service
       name: gateway-service
     target:
       type: AverageValue
       value: 5
```
I used the AverageValue because i want the metric value could be divided by current replica count, However, when i test with a tps 10, i found that metric value won't be divided as i expected. the tps metric will keep around 10 as the following screenshot, as a result, the replica count will be increased to the max value 5 which i expect it should be increased to 2. 
![image](https://user-images.githubusercontent.com/7836739/77601955-2dcd1e80-6f47-11ea-88a0-64aea21a72bf.png)

do i use the hpa in the wrong way? i think i can't use Pod metric because my hpa work in the case of scaling A service based on B service metric
