### ISSUE TITLE
External Kafka metrics causes HPA to scale too fast

### ISSUE THREAD

**Issue by lli-hiya** [kubernetes-sigs/prometheus-adapter#294]
I am using Kafka metrics as external metrics for HPA, and here is my configuration

```
    externalRules:
    - seriesQuery: 'kafka_consumer_group_lag{group!="", topic!=""}'
      resources:
        template: <<.Resource>>
      name:
        matches: "^(.*)$"
        as: "${1}_total"
      metricsQuery: 'sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)'
```
Then in my hpa, I have the following setup 
```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: sample-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: sample-app
  minReplicas: 1
  maxReplicas: 12
  - type: External
    external:
      metricName: kafka_consumer_group_lag_total
      metricSelector:
        matchLabels:
          topic: hack-mm-performance-test-source
          group: mm.hack-usw2
      targetValue: "100k"
```

However, the problem is that at any time when the metrics value is above `100k`, HPA will scale up the replicas count per a 15s(the default value of `--horizontal-pod-autoscaler-sync-period`) like this 
```
  Normal  SuccessfulRescale  11m                  horizontal-pod-autoscaler  New size: 2; reason: external metric kafka_consumer_group_lag_total(&LabelSelector{MatchLabels:map[string]string{group: mm.hack-usw2,topic: hack-mm-performance-test-source,},MatchExpressions:[],}) above target
  Normal  SuccessfulRescale  10m                  horizontal-pod-autoscaler  New size: 3; reason: external metric kafka_consumer_group_lag_total(&LabelSelector{MatchLabels:map[string]string{group: mm.hack-usw2,topic: hack-mm-performance-test-source,},MatchExpressions:[],}) above target
  Normal  SuccessfulRescale  10m                  horizontal-pod-autoscaler  New size: 4; reason: external metric kafka_consumer_group_lag_total(&LabelSelector{MatchLabels:map[string]string{group: mm.hack-usw2,topic: hack-mm-performance-test-source,},MatchExpressions:[],}) above target
  Normal  SuccessfulRescale  10m                  horizontal-pod-autoscaler  New size: 6; reason: external metric kafka_consumer_group_lag_total(&LabelSelector{MatchLabels:map[string]string{group: mm.hack-usw2,topic: hack-mm-performance-test-source,},MatchExpressions:[],}) above target
  Normal  SuccessfulRescale  10m (x2 over 3h11m)  horizontal-pod-autoscaler  New size: 12; reason: external metric kafka_consumer_group_lag_total(&LabelSelector{MatchLabels:map[string]string{group: mm.hack-usw2,topic: hack-mm-performance-test-source,},MatchExpressions:[],}) above target
```

The reason is because our Prometheus scrape interval is at `30s`, which means at two consecutive HPA queries, the metrics value is likely to be the same, and also because when the new pods are created, it takes time for it to get the Kafka topic partitions reassigned and start to do the "real work", the `kafka_consumer_group_lag_total` won't reduce immediately within that `15s` window, **causing the HPA to ALWAYS scale the replicas to its maximum within a short amount of time**. I wish that HPA could scale up to a new replica count, wait a configurable length of time and start to scale up again, but unfortunately the `--horizontal-pod-autoscaler-upscale-delay` flag on controller manager has been deprecated in Kubernetes.

So my questions are:
1. Am I doing something wrong here in terms of my setup?
2. What is the proper way to use Kafka consumer lag for HPA to avoid the problem I observed?
