### ISSUE TITLE
Custom Metric showing up at root, but can't get value. 

### ISSUE THREAD

**Issue by BenCoughlan15** [kubernetes-sigs/prometheus-adapter#299]
Hi there, 

My metric is called: mycompany_firebase_service_requests_per_second_total

my promql is: 
`  - seriesQuery: '{__name__=~"mycompany.*",kubernetes_name=~"mycompany.*"}'
    metricsQuery: "sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m]))"
    resources:
      overrides:
        kubernetes_namespace: {resource: "namespace"}
        kubernetes_pod_name: {resource: "pod"}`

When I run ` kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 | jq`

I get: 

`{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "namespaces/mycompany_firebase_service_requests_per_second_total",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}`

when I try to retrieve the actual value however: 
`kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/test-uk/pods/%2A/mycompany_firebase_service_requests_per_second_total?labelSelector=app%3Dmycompany-firebase-service%2Cnamespace%3Dtest-uk`
Error from server (NotFound): the server could not find the metric mycompany_firebase_service_requests_per_second_total for pods

Any idea where I might be looking / going wrong?

**Comment by ntkjer** [comment]
I'm having the same issue. I have the following defined in my config for the adapter
``` 
   - seriesQuery: 'nginx_ingress_controller_nginx_process_requests_total{kubernetes_namespace!="",controller_pod!="",controller_namespace!=""}'
     resources:
       #template: "app_kubernetes_<<.Resource>>"
       overrides:
         kubernetes_namespace: {resource: "namespace"}
         #app_kubernetes_io_name: {resource: "app_kubernetes_io_name"}
         controller_namespace: {resource: "namespace"}
         controller_pod: {resource: "pod"}
    name:
      matches: "^(.*)_total"
      as: "${1}_per_second"
    metricsQuery: 'sum(rate(<<.Series>>{.LabelMatchers>>}[2m]))'
```
I can also list metrics that were discovered as so:
```
❯ k get --raw /apis/custom.metrics.k8s.io/v1beta1 | jq .
{
  "kind": "APIResourceList"
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "namespaces/nginx_ingress_controller_nginx_process_requests_per_second",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
          "get"
      ] 
    }
  ]
}
```
but alas, no metric as well when I query the specified target:
```
❯ k get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/ingress-nginx/pods/*/nginx_ingress_controller_nginx_process_requests_per_second" | jq .
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/ingress-nginx/pods/%2A/nginx_ingress_controller_nginx_process_requests_per_second"
  },
  "items": []
}
```

as far as how my Prometheus query looks like: `rate(nginx_ingress_controller_nginx_process_requests_total[2m])` 
```
{app_kubernetes_io_instance="ingress-nginx",app_kubernetes_io_managed_by="Helm",
app_kubernetes_io_name="ingress-nginx-metrics",app_kubernetes_io_version="0.32.0",controller_class="nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-786b647797-crkf5",
helm_sh_chart="ingress-nginx-2.0.3",instance="10.200.97.82:10254",job="kubernetes-service-endpoints",kubernetes_name="ingress-nginx-metrics",kubernetes_namespace="ingress-nginx",kubernetes_node="ip-blah.ec2.internal"}
 
```
