### ISSUE TITLE
Prometheus outside kubernetes cluster. how to use?

### ISSUE THREAD

**Issue by wangycc** [kubernetes-sigs/prometheus-adapter#311]
i have the Following prometheus rule:
```shell
sum(rate(api_request_count{servname="gateway"}[30s])) by (servname)
```

prometheus-adapter Rule-Definition:

```yaml
    rules:
    - seriesQuery: 'api_request_count'
      resources:
        template: <<.Resource>>
        overrides:
          servname: {group: "apps", resource: "statefulset"}
      name:
        matches: "^(.*)_count"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[30s])) by (<<.GroupBy>>)'
```

and querying the metrics-api gives me the Following:

```shell
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/service/statefulsets/gateway/api_request_per_second
Error from server (NotFound): the server could not find the metric api_request_per_second for statefulsets gateway
```

prometheus adaper log(urldecode):
```shell
I0819 03:06:47.856687       1 api.go:74] GET http://sla.prometheus.pri.ibanyu.com/api/v1/query?query=sum(rate(api_request_count{namespace="service",servname="gateway"}[30s])) by (servname)&time=1597806407.851 200 OK
```

I expect to get the following query request:
```shell
sum(rate(api_request_count{servname="gateway"}[30s])) by (servname)  #Remove the namespace label

```

would be great if anyone could help me finding the correct way to get this working :)
