### ISSUE TITLE
Creating istio_requests_total custom metric for HPA 

### ISSUE THREAD

**Issue by pbn4** [kubernetes-sigs/prometheus-adapter#312]
Prometheus-adapter image:  quay.io/coreos/k8s-prometheus-adapter-amd64:v0.5.

I need some help with defining a custom metric for scaling a deployment based on total_requests_for_deployment / number_of_pods_in_replicaset. When done I think it will be useful to wider group of people. 

OK Here's what works,  but is not taking into consideration number of pods in replicaset:

```
    - seriesQuery: istio_requests_total{destination_workload!="",reporter="destination", destination_workload_namespace!=""}
      resources:
        overrides:
          destination_workload: {resource: "service"}
          destination_workload_namespace: {resource: "namespace"}
      name:
        matches: "^(.*)"
        as: "rps1m"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)'
```

now I would like to include number of pods for given workload:

```
    - seriesQuery: istio_requests_total{destination_workload!="",reporter="destination", destination_workload_namespace!=""}
      resources:
        overrides:
          destination_workload: {resource: "service"}
          destination_workload_namespace: {resource: "namespace"}
      name:
        matches: "^(.*)"
        as: "rps1m"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>) / count(kube_pod_info{created_by_name=~"<<index .LabelValuesByName "destination_workload">>-.*"})'
```

but I get the following error:

```
E0908 13:56:30.826595       1 provider.go:128] unable to fetch metrics from prometheus: bad_data: invalid parameter 'query': parse error at char 198: error parsing regexp: invalid character class range: `b-a`
```

Relevant queries and response labels:

```
Q1: kube_pod_info{created_by_name=~"trading-platform-platform-web-api.*"}

L1: kube_pod_info{created_by_kind="ReplicaSet",created_by_name="trading-platform-platform-web-api-c8f8f4ffc",host_ip="10.0.1.52",instance="10.0.2.79:8443",job="kube-state-metrics",namespace="default",node="removed",pod="trading-platform-platform-web-api-c8f8f4ffc-9srmc",pod_ip="10.0.1.195",uid="e272d3a7-3d09-41d0-9ab1-1096b1ee859c"}

Q2: istio_requests_total{destination_workload="trading-platform-platform-web-api", reporter="destination"}

L2: istio_requests_total{connection_security_policy="mutual_tls",destination_app="trading-platform-platform-web-api",destination_canonical_revision="0.0.1",destination_canonical_service="trading-platform-platform-web-api",destination_principal="spiffe://cluster.local/ns/default/sa/app",destination_service="trading-platform-platform-web-api-service.default.svc.cluster.local",destination_service_name="trading-platform-platform-web-api-service",destination_service_namespace="default",destination_version="0.0.1",destination_workload="trading-platform-platform-web-api",destination_workload_namespace="default",endpoint="9090",job="envoy-stats",namespace="istio-system",pod="prometheus-84596c7f76-8w6gj",reporter="destination",request_protocol="http",response_code="200",response_flags="-",service="prometheus",source_app="istio-ingressgateway",source_canonical_revision="latest",source_canonical_service="istio-ingressgateway",source_principal="spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account",source_version="unknown",source_workload="istio-ingressgateway",source_workload_namespace="istio-system"}
```

**Comment by Shadowssong** [comment]
@pbn4 Not sure if it would solve it for you but I was trying to solve the same thing, ran into your same issue but found another approach that works with HPA by treating it per pod instead of per service, as the HPA will know the pods in your deployment that it is attached too:

```
        - seriesQuery: istio_requests_total{pod_name!="", namespace!=""}
          resources:
            overrides:
              namespace:
                resource: namespace
              pod_name:
                resource: pod
          name:
            matches: "^(.*)_total"
            as: "${1}_per_second"
          metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
```

Because the HPA will query based on each pod it treats each metric as pod specific (there is a pod_name in the istio_requests_total metric).  Then you just need to add something like 
```
  - type: Pods
    pods:
      metric:
        name: istio_requests_per_second
      target:
        type: AverageValue
        averageValue: 5000m
``` 

to your HPA config.  Hope this helps!
