### ISSUE TITLE
Custom metrics with a cluster-scoped CRD not behaving

### ISSUE THREAD

**Issue by jackwhelpton** [kubernetes-sigs/prometheus-adapter#327]
I was hoping to use a CRD to solve a mismatch between Prometheus labels and resources in a k8s cluster, but things don't appear to be working as I expect.

I am running the adapter in a separate namespace (`kube-system`) from my app/HPA. It seems that I can only scale on a metric in the same namespace: I do not have control over the Prometheus source, so I can't add a label that directs the metric to a resource in this namespace.

Given that, one solution seems to be to run the adapter in the same namespace as the app/HPA, and create a resource in that namespace to represent the queue. However, I was hoping I could keep the separation I have by creating the queue resource at the cluster/root level.

I create a cluster-scoped CRD via something like:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queues.rabbitmq.example.com
spec:
  group: rabbitmq.example.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
  scope: Cluster
  names:
    listKind: QueueList
    plural: queues
    singular: queue
    kind: Queue
    shortNames:
    - rmq
```

I define a set of these queue objects:

```yaml
apiVersion: rabbitmq.example.com/v1alpha1
kind: Queue
metadata:
  name: my-first-queue
---
apiVersion: rabbitmq.example.com/v1alpha1
kind: Queue
metadata:
  name: my-second-queue
```

My rules look like this:

```yaml
rules:
  default: false
  custom:
  - seriesQuery: 'rabbitmq_queue_messages{cluster_name="my-cluster"}'
    resources:
      overrides:
        queue: {group: "rabbitmq.example.com", resource: "queue"}
    name:
      matches: rabbitmq_queue_messages
      as: "$0"
    metricsQuery: <<.Series>>{<<.LabelMatchers>>}
```

This creates a metric, but it appears to be namespaced and not root-scoped:

```shell
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1
```

```json
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion":"custom.metrics.k8s.io/v1beta1",
  "resources": [ 
    {
      "name": "queues.rabbitmq.example.com/rabbitmq_queue_messages",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": ["get"]
    }
  ]
}
```

Note the `namespaced: true` setting.

What URI would I use to retrieve this metric?
