### ISSUE TITLE
Custom Metrics not scaling HPA correctly, doesn't get returned on wildcard

### ISSUE THREAD

**Issue by atownsend247** [kubernetes-sigs/prometheus-adapter#342]
Hey all,

I'm currently having an issue when setting up a HPA to look at a custom metric provided from the prometheus adapter.

I have the following set in my 'values.yaml', which in my prometheus ui I can successfully query and get results for example like the following; which I believe is correct shown in the table below..

Element | Value
-- | --
logstash_node_proc_mem_load_percent_total{app="logstash-android",chart="logstash",heritage="Tiller",instance="10.5.155.78:9649",job="kubernetes-service-endpoints",kubernetes_name="logstash-android",kubernetes_namespace="monitoring",kubernetes_node="ip-10-5-158-8.eu-west-1.compute.internal",pipeline_id="android",release="logstash-android",wtr_environment="perf2",wtr_region="eu-west-1",wtr_stage="nonprod"} | 40
logstash_node_proc_mem_load_percent_total{app="logstash-android",chart="logstash",heritage="Tiller",instance="10.5.155.78:9649",job="kubernetes-service-endpoints",kubernetes_name="logstash-android",kubernetes_namespace="monitoring",kubernetes_node="ip-10-5-158-8.eu-west-1.compute.internal",pipeline_id="dlq",release="logstash-android",wtr_environment="perf2",wtr_region="eu-west-1",wtr_stage="nonprod"} | 40

'values.yaml' custom metric config.
```
rules:
  default: false
  custom: 
  - seriesQuery: '{__name__=~"logstash_node_proc_mem_load_percent_total", kubernetes_name!="",kubernetes_namespace=~"monitoring"}'
    resources:
      overrides:
        kubernetes_namespace:
          resource: namespace
        kubernetes_name:
          resource: pod 
    name:
      matches: "^(.*)_total"
      as: "${1}_avg"
    metricsQuery: (sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>))
```

I can see these when I query the custom.metrics resource:
```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" | jq '.resources[]'  | grep -B 1 -A 5 logstash                                                                               
{
  "name": "namespaces/logstash_node_proc_mem_load_percent_avg",
  "singularName": "",
  "namespaced": false,
  "kind": "MetricValueList",
  "verbs": [
    "get"
--
--
{
  "name": "pods/logstash_node_proc_mem_load_percent_avg",
  "singularName": "",
  "namespaced": true,
  "kind": "MetricValueList",
  "verbs": [
    "get"
```

However when I do the same query that the HPA does which I can see in the adapter logs it doesn't return any metrics with either of the following:
```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/pods/*/logstash_node_proc_mem_load_percent_avg?labelSelector=app%3Dlogstash-kubernetes%2Crelease%3Dlogstash-kubernetes"
{"kind":"MetricValueList","apiVersion":"custom.metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/pods/%2A/logstash_node_proc_mem_load_percent_avg"},"items":[]}

kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/pods/%2A/logstash_node_proc_mem_load_percent_avg?labelSelector=app%3Dlogstash-kubernetes%2Crelease%3Dlogstash-kubernetes"
{"kind":"MetricValueList","apiVersion":"custom.metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/pods/%2A/logstash_node_proc_mem_load_percent_avg"},"items":[]}
```

The odd thing is if I specify the pod name the results return as expected such as the below:
```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/pods/logstash-kubernetes/logstash_node_proc_mem_load_percent_avg?labelSelector=app%3Dlogstash-kubernetes%2Crelease%3Dlogstash-kubernetes"
{"kind":"MetricValueList","apiVersion":"custom.metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/pods/logstash-kubernetes/logstash_node_proc_mem_load_percent_avg"},"items":[{"describedObject":{"kind":"Pod","namespace":"monitoring","name":"logstash-kubernetes","apiVersion":"/v1"},"metricName":"logstash_node_proc_mem_load_percent_avg","timestamp":"2020-11-26T10:05:25Z","value":"200m","selector":null}]}
```

I've tried changing bits around in the values.yaml but to no avail, am I missing something? any help would be greatly appreciated :)
