### ISSUE TITLE
[Question]: Need to scale RGW pod in Rook with help of Prometheus Adapter

### ISSUE THREAD

**Issue by thotz** [kubernetes-sigs/prometheus-adapter#351]
Hi,

I was trying to setup hpa for RGW pod in my [rook](https://rook.io/) cluster in a minikube(k8s version 1.19.2) with help of [config-walkthrough.md](https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/walkthrough.md)

My Rook cluster has the following pods:
```hcl
prometheus-rook-prometheus-0                                   3/3     Running   1          4d22h
rook-ceph-mgr-a-7f4f7b979c-45746                               1/1     Running   2          4d23h
rook-ceph-mon-a-b6df566f9-lfmd5                                1/1     Running   0          4d23h
rook-ceph-operator-559b6fcf59-zprcn                            1/1     Running   4          4d23h
rook-ceph-osd-0-7b84dcd7fc-t676v                               1/1     Running   0          4d23h
rook-ceph-osd-prepare-e62527fbcc44650a4ede26b47f24c7ee-ghcvg   0/1     Pending   0          1s
rook-ceph-rgw-my-store-a-b8c88c89-kpkv5                        1/1     Running   0          4d19h
rook-ceph-tools-78cdfd976c-wsxv4                               1/1     Running   0          4d23h
```
Configured Prometheus with help of [doc](https://rook.io/docs/rook/v1.5/ceph-monitoring.html). Here required metrics for Prometheus is exported by `rook-ceph-mgr-a-7f4f7b979c-45746` and I want to scale `rook-ceph-rgw-my-store-a-b8c88c89-kpkv5`
And the metrics I am using is related to RGW `ceph_rgw_put` but is provided to prometheus via `ceph-manager` pod

I have used following cm for adapter in my set up 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: custom-metrics
data:
  config.yaml: |
    rules:
    - seriesQuery: 'ceph_rgw_put{namespace!="",pod!=""}'
      seriesFilters:
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
              #name:
              #matches: "^(.*)_put" 
              #as: "${1}_per_second"
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
```
And custom metrics were was created:
```json
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 | jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "pods/ceph_rgw_put",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "namespaces/ceph_rgw_put",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}

 kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/rook-ceph/pods/*/ceph_rgw_put | jq
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/rook-ceph/pods/%2A/ceph_rgw_put"
  },
  "items": [
    {
      "describedObject": {
        "kind": "Pod",
        "namespace": "rook-ceph",
        "name": "rook-ceph-mgr-a-7f4f7b979c-45746",
        "apiVersion": "/v1"
      },
      "metricName": "ceph_rgw_put",
      "timestamp": "2020-12-14T06:17:07Z",
      "value": "18m",
      "selector": null
    }
  ]
}
```

Now if I tried to hpa with RGW using the following:
```yaml
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: rook-ceph-rgw-my-store-a 
  namespace: rook-ceph
spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: Deployment
    name: rook-ceph-rgw-my-store-a      
  # autoscale between 1 and 10 replicas
  minReplicas: 1
  maxReplicas: 5 
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
  - type: Pods 
    pods:
      # use the metric that you used above: pods/http_requests
      metricName: ceph_rgw_put
      # target 500 milli-requests per second,
      # which is 1 request every two seconds
      targetAverageValue: 5000m
```
I am getting the following error:
```hcl
  Name:                      rook-ceph-rgw-my-store-a
Namespace:                 rook-ceph
Labels:                    <none>
Annotations:               <none>
CreationTimestamp:         Mon, 14 Dec 2020 00:47:41 -0500
Reference:                 Deployment/rook-ceph-rgw-my-store-a
Metrics:                   ( current / target )
  "ceph_rgw_put" on pods:  <unknown> / 5
Min replicas:              1
Max replicas:              5
Deployment pods:           1 current / 0 desired
Conditions:
  Type           Status  Reason               Message
  ----           ------  ------               -------
  AbleToScale    True    SucceededGetScale    the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetPodsMetric  the HPA was unable to compute the replica count: unable to get metric ceph_rgw_put: no metrics returned from custom metrics API
Events:
  Type     Reason                        Age   From                       Message
  ----     ------                        ----  ----                       -------
  Warning  FailedGetPodsMetric           12s   horizontal-pod-autoscaler  unable to get metric ceph_rgw_put: no metrics returned from custom metrics API
  Warning  FailedComputeMetricsReplicas  12s   horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get pods metric value: unable to get metric ceph_rgw_put: no metrics returned from custom metrics API
```-

If I do the same with mgr pods it works fine
```hcl
Name:                      rook-ceph-mgr-a
Namespace:                 rook-ceph
Labels:                    <none>
Annotations:               <none>
CreationTimestamp:         Mon, 14 Dec 2020 00:49:45 -0500
Reference:                 Deployment/rook-ceph-mgr-a
Metrics:                   ( current / target )
  "ceph_rgw_put" on pods:  18m / 5
Min replicas:              1
Max replicas:              5
Deployment pods:           1 current / 1 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from pods metric ceph_rgw_put
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:           <none>
```

1.  Does above means I cannot configure my hpa for RGW with custom metrics?
2.  Do I need external metrics to achieve this? if yes can you please provide a doc/steps for the same?
3.  Is external metrics are supported in Prometheus Adapter? I got following error while running kubectl api-resources
```
 :error: unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

**Comment by dgrisonnet** [comment]
Hi @thotz,

Given your use case, I'd say custom-metrics is the right choice. External metrics are intended for metrics coming from outside a Kubernetes cluster whereas in your case, the metric is coming from inside your cluster.

That being said, your misconfiguration seems to be coming from your HPA metric source type. In your case, you chose the Pods type which get metrics from all the pods controlled by your autoscaling target (rook-ceph-rgw-my-store-a). This means that when you set the target to your RGW deployment, the autoscaler will try to get the metrics from your RGW pods instead of your manager. This translates to the autoscaler querying the following endpoint:
```md
 /apis/custom.metrics.k8s.io/v1beta1/namespaces/rook-ceph/pods/*/ceph_rgw_put?labelSelector=<RGWPodLabelSelectors>
```
The labelSelector query parameter will prevent you for selecting any other resource than your autoscaling target.

Since your autoscaling target and your metric target differ, an Object type is better suited. For example, a direct translation of your previous configuration would be the following:
```
  - type: Object
    object:
      target:
        kind: Pod
        name: rook-ceph-mgr-a-7f4f7b979c-45746
      metricName: ceph_rgw_put
      targetValue: 5000m
```
Although, you will need to use another Kind of target since your pod name isn't immutable.
Does your metric has a `service` or `deployment` or any other label related to a kubernetes resource that is immutable and that we could use instead?
Note that once you change the Kind to something else (Deployment, Service) in your HPA config,  you'll also need to update the resource in your adapter configuration.

As per you two other questions, prometheus-adapter supports the external metrics API, but we don't have a documentation for it. However, there is an example here: https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/4c673534f20cc664bee0340255cc6b2ad929311e/deploy/manifests/custom-metrics-config-map.yaml#L99-L117
> I got following error while running kubectl api-resources

This error usually means that you didn't register any external metrics, thus the apiservice is not yet bind to an endpoint.

**Comment by s-urbaniak** [comment]
yes as @dgrisonnet described your use case is special as the entities exposing metrics (mgr pods) are different from your scaling target (store pods).

Is there a direct relationship between mgr pods or store pods? Could you rather scrape metrics from the store pods instead?

**Comment by thotz** [comment]
Thanks, @s-urbaniak @dgrisonnet for replying quickly. 
As per current design metrics can be scraped from MGR pods not from RGW pods, in the entire ceph cluster(includes OSD, MDS etc) metrics for Prometheus is provided by MGR pod. As you guys mentioned my case is a special case target pod and scale
 with providing suggestion IMO hpa created successfully 
```console
# kubectl -n rook-ceph describe hpa rook-ceph-rgw-my-store-a
Name:                                                                     rook-ceph-rgw-my-store-a
Namespace:                                                                rook-ceph
Labels:                                                                   <none>
Annotations:                                                              <none>
CreationTimestamp:                                                        Mon, 14 Dec 2020 13:06:56 -0500
Reference:                                                                Deployment/rook-ceph-rgw-my-store-a
Metrics:                                                                  ( current / target )
  "ceph_rgw_put" on Pod/rook-ceph-mgr-a-7f4f7b979c-45746 (target value):  18m / 5
Min replicas:                                                             1
Max replicas:                                                             5
Deployment pods:                                                          1 current / 1 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from Pod metric ceph_rgw_put
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
```
Coming to @dgrisonnet questions 
 1.) Does your metric has a service or deployment or any other label related to a kubernetes resource that is immutable and that we could use instead?

Ans: I agree with this using `podname` is not the right choice from Prometheus console the metrics I am fetching have the following info
```
ceph_rgw_put{ceph_daemon="rgw.my.store.a",endpoint="http-metrics",instance="172.17.0.5:9283",job="rook-ceph-mgr",namespace="rook-ceph",pod="rook-ceph-mgr-a-7f4f7b979c-45746",service="rook-ceph-mgr"}
```
And look like `service` will be the right choice here and change config map accordingly

```yaml
data:
  config.yaml: |
    rules:
    - seriesQuery: 'ceph_rgw_put{namespace!="",pod!="",service!=""}'
      seriesFilters:
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
          service:
            resource: "service"
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
```
I can see `services/ceph_rgw_put` in the `MetricsValuelist`
```json
# kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/ | jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "services/ceph_rgw_put",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "namespaces/ceph_rgw_put",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "pods/ceph_rgw_put",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```
But I cannot fetch the corresponding object for that entry
```console
# kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/rook-ceph/service/*/ceph_rgw_put | jq
Error from server (InternalError): Internal error occurred: unable to list matching resources
[root@rhs-srv-18 deploy]# kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/rook-ceph/services/*/ceph_rgw_put | jq
Error from server (InternalError): Internal error occurred: unable to list matching resources
```` 
So not sure how it can be mentioned as `objectMetric` in `hpa.yaml`

2.) Note that once you change the Kind to something else (Deployment, Service) in your HPA config, you'll also need to update the resource in your adapter configuration.

Hopefully, the change is done from my end for adapter configuration is right.
