### ISSUE TITLE
custom label / flattening out vectors question

### ISSUE THREAD

**Issue by justinrush** [kubernetes-sigs/prometheus-adapter#363]
I have an application that exposes the normal kubernetes_namespace and kubernetes_pod_name labels as well as a subject_name label in a gauge. I'd like to create HPA resources based on the sum of values for a specific subject_name. I'm new to looking at HPA and just set up the adapter. I'm using the community helm chart to deply it - this is what my rules looks like:
```yaml
rules:
  default: false
  custom:
    - seriesQuery: 'subject_message_count{kubernetes_namespace!="",kubernetes_pod_name!=""}'
      resources:
        overrides:
          kubernetes_namespace:
            resource: "namespace"
          kubernetes_pod_name:
            resource: "pod"
      name:
        matches: ""
        as: "subject_message_count"
      metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (subject_name, <<.GroupBy>>)
```

A query against the raw API:
`kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/test/pods/*/subject_message_count" |jq`

```json
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/test/pods/%2A/subject_message_count"
  },
  "items": [
    {
      "describedObject": {
        "kind": "Pod",
        "namespace": "test",
        "name": "server-66d9766549-vld9c",
        "apiVersion": "/v1"
      },
      "metricName": "subject_message_count",
      "timestamp": "2021-01-26T01:13:25Z",
      "value": "618",
      "selector": null
    }
  ]
}
```

I wanted to see more items, one for each subject that it finds. Can someone help me out here? or point me towards some examples that are more complex than exposing default k8s object labels?

**Comment by dgrisonnet** [comment]
For your particular use case external metrics would be better suited, custom metrics are meant to be tied to Kubernetes resources which means that only the labels you specified in the `resources` part of your config will be matched, the others will be dropped. On the contrary, external metrics are designed to autoscale based on metrics coming from outside of Kubernetes. In your case you want to autoscale based on the `subject_name` label which does not directly describe a Kubernetes resource, so you should use external metrics if you want to configure your HPA based on this data.

**Comment by justinrush** [comment]
That makes sense. Is there a good example out there to help me understand how to write the rules for external metrics?

**Comment by dgrisonnet** [comment]
The is a small example in this manifest: https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/deploy/manifests/custom-metrics-config-map.yaml#L99-L117. The syntax is very close to custom metrics, so you will not have to change a lot of things.

**Comment by justinrush** [comment]
Thanks, sorry for the late response. This is what i ended up with:

```yaml
rules:
  default: false
  external:
  - metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (subject_name, <<.GroupBy>>)
    name:
      as: subject_message_count
      matches: ""
    resources:
      overrides:
        kubernetes_namespace:
          resource: namespace
    seriesQuery: subject_message_count{kubernetes_namespace!=""}
```

This query: ` kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/test/subject_message_count?labelSelector=subject_name%3Ddefault" |jq`

Produces this output (which i can then use in HPAs):
```json
{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {},
  "items": [
    {
      "metricName": "subject_message_count",
      "metricLabels": {
        "subject_name": "default"
      },
      "timestamp": "2021-02-16T21:40:26Z",
      "value": "1"
    }
  ]
}
