### ISSUE TITLE
Custom metric selector invalid label value

### ISSUE THREAD

**Issue by pytimer** [kubernetes-sigs/prometheus-adapter#364]
Hi,
I use custom metrics hpa, my application expose `http_server_requests_seconds_count`  metric, and this metric like below:

|Element | Value|
|-- | -- |
|http_server_requests_seconds_count{application="web",endpoint="web-port",instance="192.168.10.112:8080",job="demo",method="POST",namespace="dev",pod="dev-demo-6c45bd669c-w47sj",service="demo-svc",status="200",uri="/v1/login"} | 2 |
|http_server_requests_seconds_count{application="web",endpoint="web-port",instance="192.168.10.112:8080",job="demo",method="GET",namespace="dev",pod="dev-demo-6c45bd669c-w47sj",service="demo-svc",status="200",uri="/v1/task"} | 5 |

I want my application according the uri of metric to scale up/down. I can use `selector` to filter, but label `uri` value have `/` character, i use this value as filter, hpa have the warning: `invalid label value: "/company/security/v1/account/login": at key: "uri": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')`.

How to do with selector, or use another way?

My hpa:

```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dev-demo
  namespace: dev
spec:
  maxReplicas: 2
  metrics:
  - pods:
      metric:
        name: http_server_requests_seconds_count
        selector:
          matchExpressions:
          - key: uri
            operator: In
            values:
            - /v1/task
      target:
        averageValue: "20"
        type: AverageValue
    type: Pods
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-demo
```
