### ISSUE TITLE
How to deploy multiple Prometheus-adapters in the same k8s cluster？

### ISSUE THREAD

**Issue by UrmsOne** [kubernetes-sigs/prometheus-adapter#367]
Hi. I would like to ask whether it is supported to deploy multiple Prometheus-adapters in the same cluster.

In my cluster, the knative has defined an apiservice named `custom.metrics.k8s.io/v1beta1` for HPA.
```
root@ubuntu:/workspace/gospace# kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 |jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "revisions.serving.knative.dev/concurrency",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "revisions.serving.knative.dev/rps",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```

I realized GPU metrics collection through prometheus-exporter, and now I want to deploy a Prometheus-adapter to achieve HPA 

for GPU idle rate.  How should I deal with related applications？I could make sure knative applications and  

Prometheus-adapter can run normally.

I try to modify the groupversion to `v1beta1.gpu.custom.metrics.k8s.io`, but it doesn't work properly.

```
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.gpu.custom.metrics.k8s.io
spec:
  service:
    name: custom-metrics-apiserver
    namespace: custom-metrics
  group: gpu.custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
```

Thanks for helping me to solve this.
