### ISSUE TITLE
HPA metrics using join with kube_deployment_labels

### ISSUE THREAD

**Issue by orong-pp** [kubernetes-sigs/prometheus-adapter#375]
I'm using prometheus-adapter to configure HPA for my deployment with metrics from rabbitmq-exporter
I am trying to follow this guide:
https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/config.md
and I came up with this configuration
```
prometheus-adapter:
  rules:
    default: false
    custom:
    - seriesQuery: 'rabbitmq_queue_messages'
      resources:
        overrides:
          label_app:
            resource: deployment
          namespace:
            resource: namespace
      name:
        matches: "rabbitmq_queue_messages"
        as: "celery_queue_messages"
      metricsQuery: 'label_replace(
                        kube_deployment_labels{label_celeryQueueName=~".+", label_app!~".*-apm-.*"}, "queue", "$1", "label_celeryQueueName", "(.+)"
                     ) * on (queue) group_right (label_app, namespace) rabbitmq_queue_messages'
```
and then when I run:
```
kubectl get --raw '/apis/custom.metrics.k8s.io/v1beta1/namespaces/testing/deployment/*/celery_queue_messages' | jq '.
```
I get Error from server (InternalError): `Internal error occurred: unable to list matching resources`

the issue is - the rabbitmq exporter gives me one series per queue (named rabbitmq_queue_messages) and it does not contain any labels for the deployment that the queue is related to and the namespace etc.
so the query I wrote in metricsQuery  if run in promethues it gives me 1 series per queue along with the deployment name and the namespace
and I would like to use thie series with HPA
the code above is meant to achieve that but the call to the api does not work
what am I missing here and how can I debug this issue?

**Comment by dgrisonnet** [comment]
External metrics seems to be a better fit for you use case, because as you mentioned, queues are not directly tied to a Kubernetes resources. We have an example that you might be able to customize to match your use case here: https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/deploy/manifests/custom-metrics-config-map.yaml#L99-L117.
Then, in order to select the queue you want to autoscale, you'll just have to update your HPA configuration to match a certain `label_app` value. e.g.

```
  - type: External
    external:
      metricName: "rabbitmq_queue_messages"
      metricSelector:
        matchLabels:
          label_app: myqueue
```
