### ISSUE TITLE
series_registry.go:156] metric pods/CUSTOM_METRIC (namespaced) not registered

### ISSUE THREAD

**Issue by usrlocalang** [kubernetes-sigs/prometheus-adapter#390]
K8's version 1.18

  name: prometheus-adapter
  version: 2.3.1

```yaml
    prometheus:
      url: http://prometheus-operated.monitoring
    rbac:
      create: true

    serviceAccount:
      create: true
    logLevel: 10
    rules:
      custom:
        - seriesQuery: 'django_http_requests_total_by_view_transport_method{namespace!="",pod!="",view!~"^(flcmd|prometheus).*"}'
          resources: { template: "<<.Resource>>" }
          name:
            matches: "^(.*)_total_"
            as: "${1}_per_second"
          metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)'
```
Custom Metric defined..

Executing a `kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1"` does not show me the custom metric. 

The HPA throws this error. 
![image](https://user-images.githubusercontent.com/67487986/113092058-e65d1c00-91b2-11eb-9f9c-96776abb9ad1.png)

Logs for the Adapter. 
```shell
metric pods/django_http_requests_per_second(namespaced) not registered

```
