### ISSUE TITLE
Prometheus adapter empty custom metric items

### ISSUE THREAD

**Issue by JulesBelveze** [kubernetes-sigs/prometheus-adapter#393]
EDIT: 
Hi there,
I am trying to perform HPA based on Prometheus metrics and to aggregate the metrics at a node-pool level.
To do so, I've added the following to my Prometheus adapter:
```
rules:
  default: true
  custom:
  - seriesQuery: '{__name__=~"DCGM_FI_DEV_GPU_UTIL", label_node="v100-pool"}'
    resources:
      template: <<.Resource>>
    name:
      matches: ""
      as: "v100_pool_gpu_metric"
    metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>})) by (<<.GroupBy>>)'
```
I can see that the metric is available however, the `items` list is empty:
```
>>> kubectl get --raw="/apis/custom.metrics.k8s.io/v1beta1/namespaces/dcgm-exporter/pods/*/v100_pool_gpu_metric" | jq .
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/dcgm-exporter/pods/%2A/v100_pool_gpu_metric"
  },
  "items": []
}
```

Any idea why this happens?
