### ISSUE TITLE
request： help for custom metrics with HPA. 

### ISSUE THREAD

**Issue by oldthreefeng** [kubernetes-sigs/prometheus-adapter#396]
#### What happened:

helm chart:  version: 2.3.1.

Use customer metrics but HPA not get it.

deploy use  `helm install --name prometheus-adapter --namespace monitor  stable/prometheus-adapter`

edit with custom metrics.

```
kubectl edit cm -nmonitor prometheus-adapter
    - seriesQuery: 'http_server_requests_seconds_count'
      resources: 
        overrides:
          kubernetes_namespace:
            resource: namespace
          kubernetes_pod_name:
            resource: pod
      name:
        matches: "^(.*)http_server_requests_seconds_count"
        as: "http_server_requests_seconds_count"
      metricsQuery: (sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>))
```

and I already to get wanted metrics .

```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/staging/pod/*/http_server_requests_seconds_count"  | jq . | head -n 20 
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/staging/pod/%2A/http_server_requests_seconds_count"
  },
  "items": [
    {
      "describedObject": {
        "kind": "Pod",
        "namespace": "staging",
        "name": "be-auth-service-74fc59bd49-r9v78",
        "apiVersion": "/v1"
      },
      "metricName": "http_server_requests_seconds_count",
      "timestamp": "2021-05-12T06:38:30Z",
      "value": "44m",
      "selector": null
    }
  ]
}
```

get my hpa 

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: be-auth-service
  namespace: staging
spec:
  maxReplicas: 10
  metrics:
  - pods:
      metricName: http_server_requests_seconds_count
      targetAverageValue: "50"
    type: Pods
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: be-auth-service
```
I describe hpa

```
Name:                                            be-auth-service
Namespace:                                       staging
Labels:                                          <none>
Annotations:                                     CreationTimestamp:  Wed, 21 Apr 2021 19:26:32 +0800
Reference:                                       Deployment/be-auth-service
Metrics:                                         ( current / target )
  "http_server_requests_seconds_count" on pods:  <unknown> / 50
Min replicas:                                    1
Max replicas:                                    10
Behavior:
  Scale Up:
    Stabilization Window: 0 seconds
    Select Policy: Max
    Policies:
      - Type: Percent  Value: 1  Period: 360 seconds
  Scale Down:
    Select Policy: Max
    Policies:
      - Type: Pods  Value: 1  Period: 1800 seconds
Deployment pods:    1 current / 0 desired
Conditions:
  Type           Status  Reason               Message
  ----           ------  ------               -------
  AbleToScale    True    SucceededGetScale    the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetPodsMetric  the HPA was unable to compute the replica count: did not receive metrics for any ready pods
Events:
  Type     Reason               Age                       From                       Message
  ----     ------               ----                      ----                       -------
  Warning  FailedGetPodsMetric  4m26s (x117269 over 20d)  horizontal-pod-autoscaler  did not receive metrics for any ready pods
```

pods have already to run success.

```
$ k get pod -n staging | grep be-auth-service
be-auth-service-59847fdd4-xhnhn                                1/1     Running   0          3d23h
```

#### What you expected to happen:

I want the HPA can get my wanted metrics from the adpater.

#### How to reproduce it (as minimally and precisely as possible):

a single k8s .  deploy prometheus / prometheus-adapter /  and applications.

#### Anything else we need to know?:

kubernetes version: 1.18.8
Os: Centos7.9. 

Can anyone Helps me out?
