### ISSUE TITLE
Prometheus adapter issue with metrics from external rabbitmq

### ISSUE THREAD

**Issue by neeraj201** [kubernetes-sigs/prometheus-adapter#403]
I am trying to implement HPA using external metrcis from a rabbitmq cluster hosted on AWS with an EKS cluster(v1.19) using promethues adapter.

Below works as expected
```
bash-5.1$ kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "services/rabbitmq_queue_messages_input",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
}
```

Below is the query directly to prometheus server which delivers correct data:

```
$curl  http://127.0.0.1:58102/api/v1/query?query=rabbitmq_queue_messages
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"rabbitmq_queue_messages","cluster":"RabbitMQ-cluster","durable":"true","instance":"prometheus-amqp-metrics:9419","job":"prometheus-amqp-metrics","policy":"ha-all-AWS-OWNED-DO-NOT-DELETE","queue":"input","self":"1","vhost":"vhost"},"value":[1622138944.006,"2"]}]}}
```

 "prometheus-amqp-metrics" is exporter service  in 'prometheus' namespace

Adapter rule is below:
```
    - seriesQuery: '{__name__=~"^rabbitmq_.*"}'
      seriesFilters:
      - is: ^rabbitmq_queue_messages$
      resources:
        overrides:
          job :
           resource: service
      name:
        matches: "^(.*)_messages$"
        as: "rabbitmq_queue_messages_input"
      metricsQuery: 'rate(rabbitmq_queue_messages{queue="input"})[2m]'
```

But I am not able to get the metric using below :

```
$kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/prometheus/services/prometheus-amqp-metrics/rabbitmq_queue_messages_input
Error from server (NotFound): the server could not find the metric rabbitmq_queue_messages_input for services
```
    
Not sure if it is supported on I am missing something. I have tried with k8s-prometheus-adapter-amd64:v0.6.0 and k8s-prometheus-adapter-amd64:latest
