### ISSUE TITLE
Problem getting external metrics into prom adapter

### ISSUE THREAD

**Issue by ashishranjan1457** [kubernetes-sigs/prometheus-adapter#412]
Hi,
I am trying to configure custom/external metrics from our rabbitmq cluster (non k8s) to use for autoscaling some pods in our cluster through HPA.
I am having trouble creating the rules config for the same, since I intended to use the external metrics (non-namespaced) I followed @dgrisonnet 's advice from issue: https://github.com/kubernetes-sigs/prometheus-adapter/issues/403 to create image from master  and use it. 

I was able to create the image and deploy it, I then changed the adapter config to try and add external rules, below is the config that I used:
```
data:
  config.yaml: |
    rules:
      default: "false"
      external:
      - seriesQuery: rabbitmq_queue_messages_published_total{group="rabbitmq-prod",queue="queue-name"}
        resources:
          namespaced: false
        metricsQuery: rate(<<.Series>>[10m])
```
I restarted the prom adapter pod after that but there seemed to be an error: 
```
F0625 07:12:31.297687       1 adapter.go:301] unable to load metrics discovery config: unable to load metrics discovery configuration: unable to parse metrics discovery config: yaml: unmarshal errors:
  line 2: cannot unmarshal !!map into []config.DiscoveryRule
```
Not sure what I am doing wrong here, would appreciate your help. Please find the prom-adapter pod logs attached.
[prom-adapter.txt](https://github.com/kubernetes-sigs/prometheus-adapter/files/6714288/prom-adapter.txt)

**Comment by Lord-Y** [comment]
I got the same issue than you. In version v0.8.4, namespaced is not defined in this block: https://github.com/kubernetes-sigs/prometheus-adapter/blob/b67ac3e747070887f06751ed6cfb4892d4ea08af/pkg/config/config.go#L51 VS master branch https://github.com/kubernetes-sigs/prometheus-adapter/blob/7cd63baccfc68b134ba96062d72efde87e3782cb/pkg/config/config.go#L51

**Comment by dgrisonnet** [comment]
Hi @ashishranjan1457, you have misconfigured the top-level rule. It should be:
```
data:
  config.yaml: |
    externalRules:
    - seriesQuery: rabbitmq_queue_messages_published_total{group="rabbitmq-prod",queue="queue-name"}
      resources:
        namespaced: false
      metricsQuery: rate(<<.Series>>[10m])
```
That made me notice that the documentation for external metrics is incorrect, we should replace `external:` by `externalRules:` in the examples in https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/externalmetrics.md. Anyone of you wants to open a PR to fix that?
