### ISSUE TITLE
Two metrics in seriesQuery

### ISSUE THREAD

**Issue by dgdevops** [kubernetes-sigs/prometheus-adapter#413]
Hello,

I would like to create a custom metric using PromQL query containing two metrics as seriesQuery.
The PromQL query would be the following: 
`sum(tomcat_threads_busy_threads{service!="",pod!=""}) by (pod)/sum(tomcat_threads_config_max_threads{service!="",pod!=""}) by (pod)`

Example output for the query above:
`{pod="myapps-69df74dc76-8bs59"}
`

I tried the following configuration:
```
- seriesQuery: 'sum(tomcat_threads_busy_threads{service!="",pod!=""}) by (pod)/sum(tomcat_threads_config_max_threads{service!="",pod!=""}) by (pod)'
  resources:
    overrides:
      service: {resource: "service"}
      pod: {resource: "pod"}
  name:
    matches: ^tomcat_threads_$
    as: "tomcat_threads_busy_threads_calculated"
  metricsQuery: <<.Series>>{<<.LabelMatchers>>,pod=~"myapps-.*"'}
```

Upon reloading the configuration in the adapter I get the following error:
`Error executing query: parse error at char 1: vector selector must contain label matchers or metric name
`

Is it possible to use multiple metrics in the seriesQuery?

**Comment by fpetkovski** [comment]
Hey @dgdevops, this is an error coming from prometheus. Could you set the verbosity to `-v=6` and check the query which is executed in the adapter logs?

**Comment by dgdevops** [comment]
Hello @fpetkovski,
Thanks for your response, I decided to aggregate the `tomcat_threads_busy_threads` & `tomcat_threads_config_max_threads` into one in order to have only one metric in the seriesQuery. With that approach it works fine. In case there will be need for another seriesQuery with two metrics I will test the verbosity parameter in Prometheus, thanks for the suggestion.

**Comment by fpetkovski** [comment]
Sounds great and thanks for getting back quickly. Feel free to close the issue if you have no more questions.

**Comment by TrueBurn** [comment]
@dgdevops Can you please share your config?

I am trying to add the below custom rule but when ever I do the `prometheus-adaptor` fails to start with the new config.

```
- metricsQuery: avg(avg_over_time(<<.Series>>[1m])) by (<<.GroupBy>>) / avg(avg_over_time(tomcat_threads_config_max_threads{namespace!="",
    appname!=""}[1m])) by (<<.GroupBy>>) * 100
  name:
    as: tomcat_threads_busy_threads_usage_percentage
    matches: ""
  resources:
    overrides:
      appname:
        resource: app_kubernetes_io_name
      namespace:
        resource: namespace
  seriesFilters: []
  seriesQuery: tomcat_threads_busy_threads{namespace!="",appname!=""}
```
