### ISSUE TITLE
Panic when trying to use "namespaced: false" in external rule definition 

### ISSUE THREAD

**Issue by Adamyounger** [kubernetes-sigs/prometheus-adapter#422]
Hi,

I'm trying to use the namespaced: false option for an externalRule, to auto scale on Nats (jetstream) message queues. Here is the rule definition in my config.ymal

```
externalRules:
- metricsQuery: sum(nats_consumer_num_pending{<<.LabelMatchers>>}) by (consumer_name)
  name:
    as: nats_consumer_num_pending
    matches: ""
  resources:
    namespaced: false
  seriesQuery: nats_consumer_num_pending{} 
```

This was installed using the prometheus-community/prometheus-adapter. (v2.14.2). This has installed prometheus-adapter:

directxman12/k8s-prometheus-adapter-amd64:v0.8.4

All looks good according to the docs, https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/externalmetrics.md

However I'm seeing the following panic in the K8s logs for the container

**"unable to load metrics discovery config: unable to load metrics discovery configuration: unable to parse metrics discovery config: yaml: unmarshal errors:"**

Followed by 

 **"  line 74: field namespaced not found in type config.ResourceMapping" 
"  line 81: field namespaced not found in type config.ResourceMapping"** 

I've checked https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/pkg/config/config.go, and all looks OK in the ResourceMapping struct 

```
// ResourceMapping specifies how to map Kubernetes resources to Prometheus labels
type ResourceMapping struct {
	// Template specifies a golang string template for converting a Kubernetes
	// group-resource to a Prometheus label.  The template object contains
	// the `.Group` and `.Resource` fields.  The `.Group` field will have
	// dots replaced with underscores, and the `.Resource` field will be
	// singularized.  The delimiters are `<<` and `>>`.
	Template string `json:"template,omitempty" yaml:"template,omitempty"`
	// Overrides specifies exceptions to the above template, mapping label names
	// to group-resources
	Overrides map[string]GroupResource `json:"overrides,omitempty" yaml:"overrides,omitempty"`
	// Namespaced ignores the source namespace of the requester and requires one in the query
	Namespaced *bool `json:"namespaced,omitempty" yaml:"namespaced,omitempty"`
}
```
Any help on getting this to work much appreciated.

Adam
