### ISSUE TITLE
[Help] How to query metrics with dynamic labelFilter?

### ISSUE THREAD

**Issue by kjstart** [kubernetes-sigs/prometheus-adapter#437]
I need to query pending messages on the ActiveMQ metrics, with a parameter destination.
How can I pass this destination by API requests like below? Thanks a lot!

`kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/metrics/test_query?selector=foo"`

Now I only can fix the destination in metricsQuery and if I change another destination, I need to create another query.

```
data:
  config.yaml: |
    rules:
    - seriesQuery: '{namespace!="",__name__!~"^container_.*",destination!=""}'
      seriesFilters: []
      resources:
        template: <<.Resource>>
      name:
        as: "test_query"
      metricsQuery: 'activemq_queue_queue_size{destination="foo"}'
```

**Comment by kjstart** [comment]
For example, if I create a query like this:
```
    - seriesQuery: '{namespace!="",__name__!~"^container_.*",destination!=""}'
      seriesFilters: []
      resources:
        template: <<.Resource>>
      name:
        as: "test1"
      metricsQuery: 'activemq_queue_queue_size{<<.LabelMatchers>>}'
```

When I run the query below, in the adapter log, I cannot find it queries with destination, also the result does not match.

`kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/metrics/test1?selector=destination%3DtestQueueA"`

```
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/metrics/test1"
  },
  "items": [
    {
      "describedObject": {
        "kind": "Namespace",
        "name": "default",
        "apiVersion": "/v1"
      },
      "metricName": "test1",
      "timestamp": "2021-07-20T16:24:56Z",
      "value": "2",
      "selector": null
    }
  ]
}
```

Actual data on the queue:
![image](https://user-images.githubusercontent.com/2688027/126360742-9bbfe749-5204-45a9-8d47-4631eced833c.png)
