### ISSUE TITLE
[Help] How to sum metrics?

### ISSUE THREAD

**Issue by AgustinNormand** [kubernetes-sigs/prometheus-adapter#441]
Hi, 

I need some help with this: Is it possible to sum two metrics with prometheus-adapter?
I have this two metrics in prometheus:
```
rabbitmq_queue_messages{app_kubernetes_io_instance="rabbitmq-cluster-app", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="rabbitmq", controller_revision_hash="rabbitmq-cluster-app-7c8db6c76c", helm_sh_chart="rabbitmq-8.19.2", instance="192.168.82.31:9419", job="kubernetes-pods", kubernetes_namespace="default", kubernetes_pod_name="rabbitmq-cluster-app-0", queue="tasks-to-rollback.cluster-appliers", statefulset_kubernetes_io_pod_name="rabbitmq-cluster-app-0", vhost="/"}

With value 1
```
```
rabbitmq_queue_messages{app_kubernetes_io_instance="rabbitmq-cluster-app", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="rabbitmq", controller_revision_hash="rabbitmq-cluster-app-7c8db6c76c", helm_sh_chart="rabbitmq-8.19.2", instance="192.168.82.31:9419", job="kubernetes-pods", kubernetes_namespace="default", kubernetes_pod_name="rabbitmq-cluster-app-0", queue="yaml-validated.cluster-appliers", statefulset_kubernetes_io_pod_name="rabbitmq-cluster-app-0", vhost="/"}

With value 3
```
I want to expose a metric with value 4, so I wrote this rule. That use a regex to match both queues, because their names end in "cluster-appliers"
```
- seriesQuery: 'rabbitmq_queue_messages{app_kubernetes_io_instance!="",kubernetes_namespace!="",queue=~".*.cluster-appliers"}'
  resources:
    overrides:
      kubernetes_namespace: {resource: "namespace"}
      app_kubernetes_io_instance: {resource: "service"}
  name:
    as: 'rabbitmq_queue_messages_cluster-appliers'
  metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
```
But the value that returns, is the sum of all the rabbitmq queue depths

Thank you very much!!

**Comment by AgustinNormand** [comment]
Hello, 

This is the answer:
```
- seriesQuery: 'rabbitmq_queue_messages{app_kubernetes_io_instance!="",kubernetes_namespace!="",queue=~".*.cluster-appliers"}'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          app_kubernetes_io_instance: {resource: "service"}
      name:
        as: 'rabbitmq_queue_messages_cluster-appliers'
      metricsQuery: sum(rabbitmq_queue_messages{queue=~".*cluster-appliers"}) by (<<.GroupBy>>)
```
