### ISSUE TITLE
Prometheus Adapter Query 

### ISSUE THREAD

**Issue by WoodProgrammer** [kubernetes-sigs/prometheus-adapter#450]
Hi everyone, 
I want to run that query shown at below.But when I try to reach out custom.metrics endpoint.That is returning no value like that:

results of the command

```
kubectl get --raw="/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/*/foo_metric"

{"kind":"MetricValueList","apiVersion":"custom.metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/%2A/foo_metric"},"items":[]}

```
Query Definitions:
```

  - metricsQuery: 'sum(foo_metric_key{<<.LabelMatchers>>}) by (<<.GroupBy>>) / sum(count:up1{<<.LabelMatchers>>}) by (<<.GroupBy>>)'
    resources:
      template: <<.Resource>>
    name:
      as: foo_metric
      matches: ^(.*)
    seriesQuery: '{__name__=~"foo_metric_key.*",namespace!="",pod!=""}'

```
The main problem is, when I try to run my custom query, prometheus adapter does not return any expected values.

How can I resolve that issue 

Thanks.
