### ISSUE TITLE
Empty item list but successful HTTP request

### ISSUE THREAD

**Issue by joeynaor** [kubernetes-sigs/prometheus-adapter#463]
**What happened?**:
I am getting an empty list under 'items', even though the HTTP request sent from prometheus-adapter to the prometheus server is successful and its response includes the desired data.

```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/" | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "namespaces/go_routines_total",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}


kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/*/metrics/go_routines_total" | jq .
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/%2A/metrics/go_routines_total"
  },
  "items": []
}
```

**What did you expect to happen?**:
To have 162 under 'items'.

**Please provide the prometheus-adapter config**:
<details open>
<summary>prometheus-adapter config</summary>

``` 
rules:
  default: false
  custom:
  - seriesQuery: '{__name__=~"go_routines_total"}'
    resources:
      overrides:
        job: {resource: "namespace"}
        queue: {resource: "service"}
    name:
      matches: ^(.*)
      as: "go_routines_total"
    metricsQuery: go_routines_total{job=~"rt-scrape"}
```
</details>

**Please provide the HPA resource used for autoscaling**:
No HPA configured yet.

**Please provide the HPA status**:
No HPA configured yet.

**Please provide the prometheus-adapter logs with -v=6 around the time the issue happened**:
<details open>
<summary>prometheus-adapter logs</summary>

``` 
I1018 13:33:05.254264       1 api.go:76] GET http://**.**.**.**:80/api/v1/query?query=go_routines_total%7Bjob%3D~%22rt-scrape%22%7D&time=1634563985.252&timeout= 200 OK                                                                                                        
I1018 13:33:05.254351       1 api.go:95] Response Body: {"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"go_routines_total","instance":"**.**.**.**:80","job":"rt-scrape"},"value":[1634563985.252,"162"]}]}}                               I1018 13:33:05.254743       1 httplog.go:104] "HTTP" verb="GET" URI="/apis/custom.metrics.k8s.io/v1beta1/namespaces/%2A/metrics/go_routines_total" latency="21.148501ms" userAgent="kubectl/v1.21.3 (darwin/amd64) kubernetes/ca643a4" audit-ID="cae29c7f-6915-4b49-aee3-164bbfdede9e" srcIP="10.132.0.189:44084" resp=200
```
</details>

**Environment**:
- prometheus-adapter version: v0.9.0
- prometheus version: 2.26.0
- Kubernetes version (use `kubectl version`): v1.21.3
- Cloud provider or hardware configuration: GKE
- Other info:
