### ISSUE TITLE
Metric not fetched with complex query

### ISSUE THREAD

**Issue by yevsh** [kubernetes-sigs/prometheus-adapter#464]
Prometheus adapter Rule:

```
  - seriesQuery: prop_consumer{label="test"}
      seriesFilters: []
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: prop_consumer
        as: custom_metric
      metricsQuery: sum(prop_consumer{label="test"})
```

kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" | jq .

output:
```

{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "pods/custom_metric",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
   
    {
      "name": "namespaces/custom_metric",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/the-namespace/metrics/custom_metric" | jq .

output:

`Error from server (NotFound): the server could not find the metric custom_metric for namespaces the-namespace
`
When I execute query from promotheus web-ui I see the metric.

also tried to change the rule:

```
 name:
     matches: ""
     as: "custom_metric"
     metricsQuery: 'sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)'
```

the result of: 
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/the-namespace/metrics/custom_metric" | jq .

```
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/the-namespace/metrics/custom_metric"
  },
  "items": [
    {
      "describedObject": {
        "kind": "Namespace",
        "name": "the-namespace",
        "apiVersion": "/v1"
      },
      "metricName": "custom_metric",
      "timestamp": "2021-10-24T08:47:13Z",
      "value": "-9223372036854775808m",
      "selector": null
    }
  ]
}
```
"value": "-9223372036854775808m"

which is invalid value
