### ISSUE TITLE
Unable to get request count by ingress to use on HPA

### ISSUE THREAD

**Issue by bcastilho90** [kubernetes-sigs/prometheus-adapter#468]
**What happened?**:

I'm using ingress-nginx and I'm also trying to get a rule configured correctly to return the number of requests for an ingress, however the metric is not appearing when attempting to divide value by number of pods.

**What did you expect to happen?**:

Metric to return a value.

**Please provide the prometheus-adapter config**:
<details open>
<summary>prometheus-adapter config</summary>

This works and returns the value for the whole ingress:

```
- seriesQuery: "nginx_ingress_controller_requests{}"
  seriesFilters: []
  resources:
    template: <<.Resource>>
    overrides:
      exported_namespace: {resource: "namespace"}
  name:
    matches: ""
    as: "nginx_ingress_controller_requests_per_second"
  metricsQuery: sum(irate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)
```

The HPA can use this metric just fine, but scaling wont decrease the metric number, so I attempted to do this:

```

- seriesQuery: "nginx_ingress_controller_requests{}"
  seriesFilters: []
  resources:
    template: <<.Resource>>
    overrides:
      exported_namespace: {resource: "namespace"}
  name:
    matches: ""
    as: "nginx_ingress_controller_requests_per_second"
  metricsQuery: sum(irate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)/count(kube_pod_container_status_running{container="app-name"})
```

When using this rule, the HPA gets just a 404 when querying the metric. Is there any way to accomplish this?
