### ISSUE TITLE
how to use part label

### ISSUE THREAD

**Issue by qiankunli** [kubernetes-sigs/prometheus-adapter#470]
there is a metric  `volcano_queue_allocatable_milli_gpu{instance="192.168.41.22:30005",job="volcano-scheduler",queue_name="default"} `

volcano_queue_allocatable_milli_gpu only have label `queue_name` and have not label `kubernetes_namespace`

rules:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: custom-metrics
data:
  config.yaml: |
    rules:
    - seriesQuery: volcano_queue_allocatable_milli_gpu
      resources:
        overrides:
          kubernetes_namespace:
            resource: namespace
          queue_name:
            group: scheduling.volcano.sh
            resource: queue
      metricsQuery: volcano_queue_allocatable_milli_gpu{<<.LabelMatchers>>}
```
if i use rule above, `kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/queues.scheduling.volcano.sh/dev/volcano_queue_allocatable_milli_gpu"` report  `Error from server (NotFound): the server could not find the metric volcano_queue_allocatable_milli_gpu for queues.scheduling.volcano.sh`

rules:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: custom-metrics
data:
  config.yaml: |
    rules:
    - seriesQuery: volcano_queue_allocatable_milli_gpu
      resources:
        overrides:
          kubernetes_namespace:
            resource: namespace
          queue_name:
            group: scheduling.volcano.sh
            resource: queue
      metricsQuery: volcano_queue_allocatable_milli_gpu{<<.LabelMatchers>>}
```
if i use rule above, prometheus-adapter report `E1125 12:51:59.194440       1 series_registry.go:162] unable to construct query for metric queues.scheduling.volcano.sh/volcano_queue_allocatable_milli_gpu(namespaced): unable to convert resource namespaces into label: no generic resource label form specified for this metric`

how can i query metric only by label `queue_name`
