### ISSUE TITLE
Segmentation violation thrown when using Bearer authentication

### ISSUE THREAD

**Issue by jfroment** [kubernetes-sigs/prometheus-adapter#478]
**What happened?**:

When the adapter starts, it crashes with the following error when attempting to connect to Prometheus (actually Thanos Querier) when I enable the ``--prometheus-token-file`` flag.
(the following line is the cause: https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/cmd/adapter/adapter.go#L116)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1478685]

goroutine 558 [running]:
k8s.io/client-go/transport.(*bearerAuthRoundTripper).RoundTrip(0xc00019e510, 0xc000369e00, 0xc00019e510, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.22.0/transport/round_trippers.go:298 +0x265
net/http.send(0xc000369e00, 0x237b3a0, 0xc00019e510, 0x0, 0x0, 0x0, 0xc000a2a0a0, 0x203000, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0x3195c40, 0xc000369e00, 0x0, 0x0, 0x0, 0xc000a2a0a0, 0x0, 0x1, 0xc000369e00)
	/usr/local/go/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0x3195c40, 0xc000369e00, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:585
sigs.k8s.io/prometheus-adapter/pkg/client.(*httpAPIClient).Do(0xc00000cdc8, 0x23bbf08, 0xc000052098, 0x20be845, 0x3, 0x20cb2b3, 0xe, 0xc000d23260, 0x0, 0x0, ...)
	/go/src/sigs.k8s.io/prometheus-adapter/pkg/client/api.go:64 +0x2eb
sigs.k8s.io/prometheus-adapter/pkg/client/metrics.(*instrumentedGenericClient).Do(0xc0004455c0, 0x23bbf08, 0xc000052098, 0x20be845, 0x3, 0x20cb2b3, 0xe, 0xc000d23260, 0x0, 0x0, ...)
	/go/src/sigs.k8s.io/prometheus-adapter/pkg/client/metrics/metrics.go:69 +0x1d6
sigs.k8s.io/prometheus-adapter/pkg/client.(*queryClient).Series(0xc00027a2e0, 0x23bbf08, 0xc000052098, 0x17e357cedf1, 0x0, 0xc00072d280, 0x1, 0x1, 0xc00002b8c0, 0xc000556f30, ...)
	/go/src/sigs.k8s.io/prometheus-adapter/pkg/client/api.go:163 +0x1f7
sigs.k8s.io/prometheus-adapter/pkg/custom-provider.(*cachingMetricsLister).updateMetrics.func1(0xc00044fb30, 0x17e357cedf1, 0xc0007224b0, 0x45, 0xc000778ea0, 0xc000778e40)
	/go/src/sigs.k8s.io/prometheus-adapter/pkg/custom-provider/provider.go:259 +0xe2
created by sigs.k8s.io/prometheus-adapter/pkg/custom-provider.(*cachingMetricsLister).updateMetrics
	/go/src/sigs.k8s.io/prometheus-adapter/pkg/custom-provider/provider.go:258 +0x9da
```

**What did you expect to happen?**:

I expected to see Prometheus Adapter successfully connect to Prometheus/Thanos.

**Please provide the prometheus-adapter config**:
<details open>
<summary>prometheus-adapter config</summary>

![image](https://user-images.githubusercontent.com/2869798/148580217-e0ef051a-8f56-401a-ad03-f9fe1da2369e.png)
I also tried to directly mount the token using ``--prometheus-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token`` but same result.

The config is pretty standard, I use Helm for deployment, here is my values.yaml file:

![image](https://user-images.githubusercontent.com/2869798/148580599-0d707f6b-a1a6-4a2d-986d-67ac221e7fb8.png)

</details>

**Anything else we need to know?**:

If this flag cannot be used how can I set up Authentication using Bearer token? I have a working Grafana connecting on the same Thanos as a datasource using the Bearer Token method, but I keep getting 403 Forbidden errors on the Adapter.
I also tried ``--prometheus-header`` parameter but it does nothing (still 403).

**Environment**:
- prometheus-adapter version: v0.9.1
- prometheus version: Thanos Querier 0.20.2
- Kubernetes version (use `kubectl version`): OpenShift 4.8.7 (k8s v1.21)
- Cloud provider or hardware configuration: On-Prem amd64
- Other info: -

**Comment by Eric-918** [comment]
anyone help ?

**Comment by olivierlemasle** [comment]
Yes, there's a bug with `--prometheus-token-file`.

Please see #538 for a fix.
You may test the fix with the image `quay.io/olivierlemasle/prometheus-adapter-amd64`.

### Workaround 1
However, there's a workaround: you can use `--prometheus-auth-config` instead.

For example, if your token is in `/var/run/secrets/kubernetes.io/serviceaccount/token` and you certificate authority in `/etc/ssl/certs/service-ca.crt`, create this ConfigMap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-prometheus-config
data:
  prometheus-config.yaml: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /etc/ssl/certs/service-ca.crt
        server: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
      name: prometheus-k8s
    contexts:
    - context:
        cluster: prometheus-k8s
        user: prometheus-k8s
      name: prometheus-k8s
    current-context: prometheus-k8s
    kind: Config
    preferences: {}
    users:
    - name: prometheus-k8s
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```

Then mount this configmap in your prometheus-adapter pod, with `mountPath` = `/etc/prometheus-config`, and to args:

```
--prometheus-auth-config=/etc/prometheus-config/prometheus-config.yaml
```

There was actually a discussion abound the feature duplication between `--prometheus-auth-config` and `--prometheus-token-file`: see #144.

### Workaround 2

Just for the sake of completeness, you can use `--prometheus-header`, as you tried @jfroment.

This works:
```bash
--prometheus-header=Authorization=Bearer content_of_the_token
```
However, this does not work:
```bash
--prometheus-header=Authorization=Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
```

I suppose it does not work simply because `cat` is not available in the Distroless-based image.

---
/remove-lifecycle rotten

**Comment by james-callahan** [comment]
I also ran into this issue.

Previously I was attempting:
```yaml
        template:
          spec:
            containers:
              - name: prometheus-adapter
                env:
                  - name: PROMETHEUS_TOKEN_FILE
                    value: /etc/adapter/secret/bearer-token
                volumeMounts:
                  - mountPath: /etc/adapter/secret
                    name: secret
                    readOnly: true
            volumes:
              - name: secret
                secret:
                  secretName: secret
```

but instead have swapped to:
```yaml
        template:
          spec:
            containers:
              - name: prometheus-adapter
                env:
                  - name: PROMETHEUS_BEARER_TOKEN
                    valueFrom:
                      secretKeyRef:
                        name: secret
                        key: bearer-token
                  - name: PROMETHEUS_HEADER
                    value: Authorization=Bearer $(PROMETHEUS_BEARER_TOKEN)
```

i.e. using workaround #2 as mentioned by @olivierlemasle


---

It appears that a fix has been merged, but no release? (and it has been several months)
