### ISSUE TITLE
error creating self-signed certificates: open /var/run/serving-cert/apiserver.crt: permission denied

### ISSUE THREAD

**Issue by chymy** [kubernetes-sigs/prometheus-adapter#479]
**What happened?**:
When I deploy `kube-prometheus-0.10.0` on k8s, `prometheus-adapter` pod status is `CrashLoopBackOff`:

**What did you expect to happen?**:
`prometheus-adapter` runs successfully.
**Please provide the prometheus-adapter config**:
<details open>
<summary>prometheus-adapter config</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: metrics-adapter
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.9.1
  name: prometheus-adapter
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics-adapter
      app.kubernetes.io/name: prometheus-adapter
      app.kubernetes.io/part-of: kube-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: metrics-adapter
        app.kubernetes.io/name: prometheus-adapter
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 0.9.1
    spec:
      containers:
      - args:
        - --cert-dir=/var/run/serving-cert
        - --config=/etc/adapter/config.yaml
        - --logtostderr=true
        - --metrics-relist-interval=1m
        - --prometheus-url=http://prometheus-k8s.monitoring.svc:9090/
        - --secure-port=6443
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA
        image: kubernetes-release-docker.artsz.zte.com.cn/addons/prometheus-adapter/prometheus-adapter:v0.9.1
        name: prometheus-adapter
        ports:
        - containerPort: 6443
        resources:
          limits:
            cpu: 250m
            memory: 180Mi
          requests:
            cpu: 102m
            memory: 180Mi
        volumeMounts:
        - mountPath: /tmp
          name: tmpfs
          readOnly: false
        - mountPath: /var/run/serving-cert
          name: volume-serving-cert
          readOnly: false
        - mountPath: /etc/adapter
          name: config
          readOnly: false
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: prometheus-adapter
      volumes:
      - emptyDir: {}
        name: tmpfs
      - emptyDir: {}
        name: volume-serving-cert
      - configMap:
          name: adapter-config
        name: config

```

</details>

**Please provide the HPA resource used for autoscaling**:
<details open>
<summary>HPA yaml</summary>

</details>

**Please provide the HPA status**:

**Please provide the prometheus-adapter logs with -v=6 around the time the issue happened**:
<details open>
<summary>prometheus-adapter logs</summary>

```
I0111 03:09:45.410954       1 adapter.go:108] successfully using in-cluster auth
F0111 03:09:50.918620       1 adapter.go:334] unable to install resource metrics API: error creating self-signed certificates: open /var/run/serving-cert/apiserver.crt: permission denied
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000182001, 0xc000788000, 0xbb, 0x1d0)
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x31979e0, 0xc000000003, 0x0, 0x0, 0xc00023ca80, 0x0, 0x2853ceb, 0xa, 0x14e, 0x0)
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:975 +0x1e5
k8s.io/klog/v2.(*loggingT).printf(0x31979e0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x20fc87f, 0x2a, 0xc00027c1b0, 0x1, ...)
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:753 +0x19a
k8s.io/klog/v2.Fatalf(...)
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1514
main.main()
        /go/src/sigs.k8s.io/prometheus-adapter/cmd/adapter/adapter.go:334 +0xa66

goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x31979e0)
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:420 +0xdf

goroutine 97 [select]:
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x21a20e8, 0x237a940, 0xc000593740, 0x1, 0xc000170060)
        /go/pkg/mod/k8s.io/apimachinery@v0.22.0/pkg/util/wait/wait.go:167 +0x118
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x21a20e8, 0x12a05f200, 0x0, 0xc000225901, 0xc000170060)
        /go/pkg/mod/k8s.io/apimachinery@v0.22.0/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.22.0/pkg/util/wait/wait.go:90
k8s.io/apimachinery/pkg/util/wait.Forever(0x21a20e8, 0x12a05f200)
        /go/pkg/mod/k8s.io/apimachinery@v0.22.0/pkg/util/wait/wait.go:81 +0x4f
created by k8s.io/component-base/logs.InitLogs
        /go/pkg/mod/k8s.io/component-base@v0.22.0/logs/logs.go:58 +0x8a

goroutine 99 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x45

goroutine 100 [chan receive]:
k8s.io/apiserver/pkg/server.SetupSignalContext.func1(0xc000302e40)
        /go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/server/signal.go:48 +0x36
created by k8s.io/apiserver/pkg/server.SetupSignalContext
        /go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/server/signal.go:47 +0xf3

goroutine 105 [IO wait]:
internal/poll.runtime_pollWait(0x7f6139145770, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00002ed18, 0x72, 0x4600, 0x464f, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00002ed00, 0xc000610000, 0x464f, 0x464f, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc00002ed00, 0xc000610000, 0x464f, 0x464f, 0x4564, 0xc0006100e6, 0x5)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00011be40, 0xc000610000, 0x464f, 0x464f, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc0003b3218, 0xc000610000, 0x464f, 0x464f, 0x4564, 0xc000070400, 0xc000390f00)
        /usr/local/go/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc0001ad078, 0x2377840, 0xc0003b3218, 0x40b8c5, 0x1e23300, 0x203ff20)
        /usr/local/go/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc0001ace00, 0x237b5c0, 0xc00011be40, 0x5, 0xc00011be40, 0x206)
        /usr/local/go/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0001ace00, 0x0, 0x0, 0xc000431bb8)
        /usr/local/go/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc0001ace00, 0xc0003b9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc00038fec0, 0xc0001622d8, 0x9, 0x9, 0x93e5cb, 0xc000431c78, 0x406fa5)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x23776a0, 0xc00038fec0, 0xc0001622d8, 0x9, 0x9, 0x9, 0xc00064b160, 0xb0fdd8be41e000, 0x117)
        /usr/local/go/src/io/io.go:328 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader(0xc0001622d8, 0x9, 0x9, 0x23776a0, 0xc00038fec0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20210520170846-37e1c6afe023/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001622a0, 0xc0007866c0, 0x0, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20210520170846-37e1c6afe023/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000431fa8, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20210520170846-37e1c6afe023/http2/transport.go:1821 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000390d80)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20210520170846-37e1c6afe023/http2/transport.go:1743 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
        /go/pkg/mod/golang.org/x/net@v0.0.0-20210520170846-37e1c6afe023/http2/transport.go:695 +0x6c5
```

</details>

**Anything else we need to know?**:

**Environment**:
- prometheus-adapter version: 
- prometheus version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:
