### ISSUE TITLE
unable to get metric istio_requests_per_second

### ISSUE THREAD

**Issue by pandagodyyy** [kubernetes-sigs/prometheus-adapter#483]
Hi,

I'm trying set HPA for metrics istio_requests_per_second on service level. but it does not work.
I'm using helm chart to deploy the prometheus-adapter, configuration as below:
```
        values:
          prometheus:
            url: http://prometheus-stack-infra-dev-prometheus.sre-stack.svc
            port: 9090
            path: ""
          rules:
            default: false
            custom:
              - seriesQuery: istio_requests_total{destination_service_name!="",reporter="destination", destination_workload_namespace!=""}
                resources:
                  overrides:
                    destination_service_name: {resource: "service"}
                    destination_workload_namespace: {resource: "namespace"}
                name:
                  matches: "^(.*)_total"
                  as: "${1}_per_second"
                metricsQuery: 'round(sum(rate(<<.Series>>{reporter="destination", <<.LabelMatchers>>}[2m])) by (destination_service_name), 0.001)'
```
my HPA configuration is 
```
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: istio_requests_per_second
      describedObject:
        apiVersion: v1
        kind: Service
        name: notificaton
      target:
        type: AverageValue
        value: 5
```
When I generated load into target service, I could see incoming requests from the dashboard
![image](https://user-images.githubusercontent.com/61133973/151201478-d9f46dfe-f7e7-47af-bdbe-aa47e9e136aa.png)

however when I check the HPA status by "kubectl describe", it was always complaining 
`  Warning  FailedGetObjectMetric  4m10s (x816 over 7h1m)  horizontal-pod-autoscaler  unable to get metric istio_requests_per_second: Service on main notificaton/unable to fetch metrics from custom metrics API: the server could not find the metric istio_requests_per_second for services notificaton`

Then I also checked "kubectl proxy", I was able to see custom metrics with url http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1/
![image](https://user-images.githubusercontent.com/61133973/151199922-e1ddce25-5dd3-4c80-9825-e9ab139e723e.png)
but I got 404 with url http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1/namespaces/main/services/notification/istio_requests_per_second
![image](https://user-images.githubusercontent.com/61133973/151200947-654cd843-1705-43d1-b88c-7d8e8838088a.png)

Reached here, I have no idea why it is not found, Can you give me some suggestion or give some steps to check root cause 

Notes. my cluster has metrics-server installed by default, not sure if it will cause this
