### ISSUE TITLE
Added Rule for Nginx Ingress Shows no Resources

### ISSUE THREAD

**Issue by afrazkhan** [kubernetes-sigs/prometheus-adapter#493]
**What happened?**: I've added some rules to capture Nginx ingress metrics, but see no results from the API (details below).

**What did you expect to happen?**: See results from a query to `/apis/custom.metrics.k8s.io/v1beta1`. What I actually see is:

```
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": []
}
```

**Please provide the prometheus-adapter config**:
<details open>
<summary>prometheus-adapter config</summary>

```
    - seriesQuery: '{__name__=~"^nginx_ingress_controller_requests.*",namespace!=""}'
      seriesFilters: []
      resources:
        template: <<.Resource>>
        overrides:
          namespace:
            resource: "namespace"
      name:
        matches: ""
        as: "nginx_ingress_controller_requests_rate"
      metricsQuery: round(sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>), 0.001)
```

I've also tried being greedier with the query; `"^nginx_.*"`.

</details>

**Please provide the HPA resource used for autoscaling**:
<details open>
<summary>HPA yaml</summary>

Not relevant, didn't get that far.

</details>

**Please provide the HPA status**: N/A

**Please provide the prometheus-adapter logs with -v=6 around the time the issue happened**:
<details open>
<summary>prometheus-adapter logs</summary>

I'll add more as requested, but for now I'll just post what I believe is pertinent, which is that I _do_ see lines like this:

```
I0317 08:17:01.370711       1 api.go:76] GET http://prometheus-server.monitoring.svc:80/api/v1/series?match%5B%5D=%7B__name__%3D~%22%5Enginx_ingress_controller_requests.%2A%22%2Cnamespace%21%3D%22%22%7D&start=1647504961.368 200 OK
```

</details>

**Anything else we need to know?**:

**Environment**:
- prometheus-adapter version: Tag v0.9.1 from k8s.gcr.io/prometheus-adapter/prometheus-adapter
- prometheus version: 2.26.0
- Kubernetes version (use `kubectl version`): 1.19
- Cloud provider or hardware configuration: AWS, running on EKS
- Other info: Deployed via Helm
