### ISSUE TITLE
No resources are found after setting up adapter with a forward rule for a custom metric.

### ISSUE THREAD

**Issue by dmccoystephenson** [kubernetes-sigs/prometheus-adapter#503]
Hello! I am attempting to use the Prometheus Adapter to forward some queries for custom metrics to Prometheus. The metrics are available in Prometheus, but when I attempt to list them through the custom metrics API, no resources are found.

This is the rules section of my values file:
```
rules:
  custom:
     - seriesQuery: '{__name__=~"kafka_consumergroup_group_sum_lag"}'
       resources:
         template: <<.Resource>>
       name:
         matches: "kafka_consumergroup_group_sum_lag"
         as: "{$1} seconds"
       metricsQuery: kafka_consumergroup_group_sum_lag{group="AsnDecode"}
```

This is the command I'm using to check my work:
```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1"
```
This is the output I get:
```
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"custom.metrics.k8s.io/v1beta1","resources":[]}
```

Have I misconfigured anything? What should I do from here?
