### ISSUE TITLE
Are externalRules still supported in v0.9.1?

### ISSUE THREAD

**Issue by data-dude** [kubernetes-sigs/prometheus-adapter#504]
I tried configuring external rules and the Prometheus Adapter doesn't complain but when I query the api or just show all the apis i don't see the api (/apis/external.metrics.k8s.io/v1beta1/) is available.

configuration follows:

```
rules:
<stuff here>
externalRules:
- seriesQuery: '{__name__:'my_metric_name'}
  resources:
    namespaced:  false
  metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
```
