### ISSUE TITLE
No Namespace Queries not working

### ISSUE THREAD

**Issue by aroelo** [kubernetes-sigs/prometheus-adapter#530]
I'm trying to use an external metric to scale a workload using the HPA, but the external metric is in a different namespace than the workload.

I have set up the external rule as described in the docs here: https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/externalmetrics.md#namespacing

In my case like this:
```
    - seriesQuery: 'queueSize{queue=~"my_queue_.*"}'
      resources:
        namespaced: false
      metricsQuery: 'sum(<<.Series>>{<<.LabelMatchers>>, queue=~"my_queue_.*"}) by (<<.GroupBy>>)'
```

However when I list the metrics it still says that it is namespaced, from the output of `kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1"`:
```
    {
      "name": "queueSize",
      "singularName": "",
      "namespaced": true,
      "kind": "ExternalMetricValueList",
      "verbs": [
        "get"
      ]
    } 
```
I'm using the latest release (v0.10.0) for the prometheus adapter.

Could anyone help me figure out why this keeps using the namespace in the query? Am I missing something?

**Comment by shubham-bansal96** [comment]
I am facing same issue. Below mentioned is my configuration for prometheus.

```
rules:
  default: false
  external:
  - seriesQuery: '{__name__="http_requests_total",path!="",job="router"}'
    metricsQuery: '(sum (rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by(path))'  
    resources:
      namespaced: false
```

Output
```
kubectl get --raw /apis/external.metrics.k8s.io/v1beta1

{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "http_requests_total",
      "singularName": "",
      "namespaced": true,
      "kind": "ExternalMetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```
