### ISSUE TITLE
External metrics do not appear

### ISSUE THREAD

**Issue by mmasiuk** [kubernetes-sigs/prometheus-adapter#537]
Hey Team,

I observe strange situation. Few weeks ago I have configure some external metrics.
They worked just fine. HPA as well. But yesterday it stopped working.
I have tried to reinstall helm chart for adapter and then I do not see my metrics anymore.

```
kubectl get --raw /apis/external.metrics.k8s.io/v1beta1 | jq

{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": []
}
```

This is one of my metrics:

```
rules:
  external:
    - seriesQuery: 'nginx_ingress_controller_requests{namespace="ingress-controller",ingress="classification-dev-core-ingress"}'
      resources:
        namespaced: false
      name:
        matches: ""
        as: "classification-dev-core-requests-per-min"
      metricsQuery: 'sum(irate(nginx_ingress_controller_requests{ingress="classification-dev-core-ingress"}[2m]))*60'
```

Also metrics appears on related configmap.

Any particular reason for that? Or things that I can check to identify root cause?
Many thanks in advance for your support here.
