### ISSUE TITLE
Cannot get custom metric

### ISSUE THREAD

**Issue by jimitkr** [kubernetes-sigs/prometheus-adapter#548]
I've been trying to setup HPA based on AWS SQS queue depth using prometheus adapter for a while now. All configuration looks correct but i still cannot get past the below error. What am i doing wrong?

`Warning  FailedComputeMetricsReplicas  8s (x6 over 83s)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get object metric value: unable to get metric approximate_number_of_messages: Service on <namespace1> <metric1>/unable to fetch metrics from custom metrics API: the server could not find the metric approximate_number_of_messages for services`

Notes: 
-- Prometheus service is running in prometheus namespace
-- Prometheus adapter is installed in monitoring namespace
-- Application service that requires scaling (service1) is running in namespace1
-- I've skipped listing some RBAC resources since they have annotations internal to my firm. In any case i don't think roles are a problem, since the error i get does not indicate an issue tied to access. 

**PROMETHEUS ADAPTER RESOURCES**

**configmap.yml**
```

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
    - seriesQuery: 'approximate_number_of_messages{kubernetes_namespace!="",kubernetes_pod_name!=""}'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "pod"}
      name:
        matches: "approximate_number_of_messages"
        as: "approximate_number_of_messages"
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container_name!="POD"}[1m])) by (<<.GroupBy>>)
```

**custom_metric_apiservice.yml**
```
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: prometheus-adapter
    namespace: monitoring
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
```

**deployment.yml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus-adapter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: prometheus-adapter
    spec:
      containers:
        - args:
            - --cert-dir=/var/run/serving-cert
            - --config=/etc/adapter/config.yaml
            - --logtostderr=true
            - --metrics-relist-interval=1m
            - --prometheus-url=http://prometheus-service.prometheus.svc:9090/
            - --secure-port=6443
          image: <image_uri>
          name: prometheus-adapter
          ports:
            - containerPort: 6443
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs
              readOnly: false
            - mountPath: /var/run/serving-cert
              name: volume-serving-cert
              readOnly: false
            - mountPath: /etc/adapter
              name: config
              readOnly: false
      serviceAccountName: prometheus-adapter
      volumes:
        - emptyDir: {}
          name: tmpfs
        - emptyDir: {}
          name: volume-serving-cert
        - configMap:
            name: prometheus-adapter-config
          name: config
```

**networkpolicy.yml**
```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: default.permit-prom-adaptor-api-access-app
  namespace: monitoring
spec:
  order: 301
  #selector: name == 'prometheus-adapter'
  types:
    - Egress
  egress:
    - action: Allow
      destination:
        namespaceSelector: all()
        selector: endpoints.projectcalico.org/serviceName == 'kubernetes' && provider == 'kubernetes' && component == 'apiserver' && projectcalico.org/namespace == 'default'
        ports:
          - 443
      protocol: TCP
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: default.permit-adaptor-to-prometheus
  namespace: monitoring
spec:
  order: 301
  types:
    - Egress
  egress:
    - action: Allow
      protocol: TCP
      destination:
        namespaceSelector: prometheus == 'monitor'
        ports:
          - 9090
```

**prometheus_adapter_service.yml**
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus-adapter
  name: prometheus-adapter
  namespace: monitoring
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
  selector:
    name: prometheus-adapter
```

**APPLICATION SERVICE RESOURCES**

**deployment.yml**
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    prometheus: monitor
  name: namespace1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: namespace1
spec:
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8443'
        prometheus.io/path: /queue_messages
    spec:
      securityContext:
        runAsUser: 999
      imagePullSecrets:
        - name: regcred
      serviceAccountName: service1-sa
      containers:
        - name: service1
          image: <image_uri>
          ports:
            - containerPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-worker
  namespace: namespace1
spec:
  selector:
    matchLabels:
      app: service1-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: service1-worker
    spec:
      securityContext:
        fsGroup: 99
        runAsNonRoot: true
        runAsUser: 99
      imagePullSecrets:
        - name: regcred
      containers:
        - name: service1-worker
          image: <image_uri>
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
```

**hpa.yml**
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: service1-hpa
  namespace: namespace1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service1
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Object
      object:
        metric:
          name: approximate_number_of_messages
        describedObject:
          apiVersion: v1
          kind: Service
          name: service1
        target:
          type: Value
          value: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
```

**service.yml**
```
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: namespace1
  labels:
    app: service1
spec:
  ports:
    - name: metrics
      port: 9090
      targetPort: 8443
      protocol: TCP
  selector:
    app: service1
```

**service_monitor.yml**
```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service1
  namespace: namespace1
  labels:
    prometheus: monitor
spec:
  namespaceSelector:
    matchNames:
      - namespace1
  selector:
    matchLabels:
      app: service1
  endpoints:
    - port: metrics
      path: /queue_messages
```

**LOGS**

## HPA events - ERROR ##
```
  Type           Status  Reason                 Message
  ----           ------  ------                 -------
  AbleToScale    True    SucceededGetScale      the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetObjectMetric  the HPA was unable to compute the replica count: unable to get metric approximate_number_of_messages: Service on namespace1 service1/unable to fetch metrics from custom metrics API: the server could not find the metric approximate_number_of_messages for services
Events:
  Type     Reason                        Age               From                       Message
  ----     ------                        ----              ----                       -------
  Warning  FailedGetObjectMetric         8s (x6 over 83s)  horizontal-pod-autoscaler  unable to get metric approximate_number_of_messages: Service on namespace1 service1/unable to fetch metrics from custom metrics API: the server could not find the metric approximate_number_of_messages for services
  Warning  FailedComputeMetricsReplicas  8s (x6 over 83s)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get object metric value: unable to get metric approximate_number_of_messages: Service on namespace1 service1/unable to fetch metrics from custom metrics API: the server could not find the metric approximate_number_of_messages for service
```

## Container is publishing the metric successfully. Below are results from running the command in the container ##

```
appuser@container[service1-xxxxx-xxxxx]:/# curl http://localhost:8443/queue_messages

approximate_number_of_messages 0
```

## Custom metric - NO METRIC LISTED ##
```
kubectl get --raw="/apis/custom.metrics.k8s.io/v1beta1/"
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"custom.metrics.k8s.io/v1beta1","resources":[]
```

**Comment by jlange-koch** [comment]
Hi,
we had the same issue and the solution was in the config.yaml. We made the following changes:

`    rules:
    - seriesQuery: 'approximate_number_of_messages{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}`

(basically "removing" the overrides). After that it all worked fine.

**Comment by jimitkr** [comment]
@jlange-koch But you still have the overrides in your snippet above. Did you mean to remove the `overrides:` tags?

**Comment by jimitkr** [comment]
@olivierlemasle  I figured out the problem. Here is how i fixed the issue:

1. ServiceMonitor and Prometheus annotations cause conflict if used together. I removed the annotations and switched to Service Monitor only
~~prometheus.io/scrape: 'true'~~
  ~~prometheus.io/port: '8443'~~
  ~~prometheus.io/path: /queue_messages~~

2. I updated my ConfigMap overrides to use 
`kubernetes_namespace` instead of `namespace`
`kubernetes_pod_name` instead of `pod`

like so:
```
- seriesQuery: 'approximate_number_of_messages{kubernetes_namespace!="",kubernetes_pod_name!=""}'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "pod"}
```
