### ISSUE TITLE
missing CPU for node "xxx", skipping

### ISSUE THREAD

**Issue by nenych** [kubernetes-sigs/prometheus-adapter#549]
**What happened?**:
Can't make kubectl top node work
**What did you expect to happen?**:

**Please provide the prometheus-adapter config**:
<details open>
<summary>prometheus-adapter config</summary>

```
resourceRules:
  cpu:
    containerLabel: container
    containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, container!=""}[3m]))
      by (<<.GroupBy>>)
    nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[3m]))
      by (<<.GroupBy>>)
    resources:
      overrides:
        namespace:
          resource: namespace
        node:
          resource: node
        pod:
          resource: pod
  memory:
    containerLabel: container
    containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>, container!=""})
      by (<<.GroupBy>>)
    nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>, id="/"})
      by (<<.GroupBy>>)
    resources:
      overrides:
        namespace:
          resource: namespace
        node:
          resource: node
        pod:
          resource: pod
  window: 1m
```

</details>

**Please provide the HPA resource used for autoscaling**:
<details open>
<summary>HPA yaml</summary>

Does not meter, I have no node resources

</details>

**Please provide the HPA status**:
Does not meter

**Please provide the prometheus-adapter logs with -v=6 around the time the issue happened**:
<details open>
<summary>prometheus-adapter logs</summary>

I1208 15:15:14.926535       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping
I1208 15:15:14.926544       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping
I1208 15:15:14.926555       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping
I1208 15:15:14.926564       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping
I1208 15:15:14.926572       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping
I1208 15:15:14.926882       1 httplog.go:131] "HTTP" verb="LIST" URI="/apis/metrics.k8s.io/v1beta1/nodes" latency="3.65278ms" userAgent="kubectl/v1.23.3 (darwin/arm64) kubernetes/816c97a" audit-ID="8d1396ec-b420-46b2-8959-8ed9bfe123b4" srcIP="10.21.80.171:34326" resp=200
I1208 15:15:15.957861       1 handler.go:143] prometheus-metrics-adapter: GET "/apis/metrics.k8s.io/v1beta1/nodes" satisfied by gorestful with webservice /apis/metrics.k8s.io/v1beta1
I1208 15:15:15.961470       1 api.go:90] GET http://monitoring-kube-prometheus-prometheus.mgmt.svc:9090/api/v1/query?query=sum%28container_memory_working_set_bytes%7Bnode%3D~%22ip-10-21-221-138.ca-central-1.compute.internal%7Cxxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%22%2Cid%3D%27%2F%27%7D%29+by+%28node%29&time=1670512515.958 200 OK
I1208 15:15:15.961484       1 api.go:90] GET http://monitoring-kube-prometheus-prometheus.mgmt.svc:9090/api/v1/query?query=sum%28rate%28container_cpu_usage_seconds_total%7Bnode%3D~%22xxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%7Cxxxxxxxxxxxxxxxxxxxxxx%22%2C+id%3D%27%2F%27%7D%5B3m%5D%29%29+by+%28node%29&time=1670512515.958 200 OK
I1208 15:15:15.962225       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping
I1208 15:15:15.962242       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping
I1208 15:15:15.962252       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping
I1208 15:15:15.962261       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping
I1208 15:15:15.962271       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping
I1208 15:15:15.962284       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping
I1208 15:15:15.962294       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping
I1208 15:15:15.962309       1 provider.go:293] missing CPU for node "xxxxxxxxxxxxxxxxxxxxxx", skipping

</details>

**Anything else we need to know?**:
The problem is with query container_cpu_usage_seconds_total{<<.LabelMatchers>>,id='/'}[4m], cadvisor does not response with id="/", I have a lot of ids like:

/kubepods/besteffort/pod2761ccbb-07c5-44ae-b841-8a570f569915

/kubepods/besteffort/pod016611cc-9081-4e1a-b55c-19f402038cb9/4a133e441a3ec3960e63594c32f9a78dea021c712de0bdaa4bc7...

**Environment**:
- prometheus-adapter version: v0.10.0
- prometheus version:  v2.39.1
- Kubernetes version (use `kubectl version`): 1.23
- Cloud provider or hardware configuration: AWS EKS
- Other info:
