### ISSUE TITLE
How to manage config in a reusable/scalable way

### ISSUE THREAD

**Issue by jw-s** [kubernetes-sigs/prometheus-adapter#558]
Hi team, first and foremost thank you for this great project. I think it is safe to say that many folk were thinking how cool it would be to scale on metrics coming from prometheus. Kudos!

# Background
We are a team of k8s administrators who provide tailored k8s clusters to our development teams, aiming for a self-service platform, integrations to our company's systems and utilising open source tooling where it makes sense for adds on to k8s.
Our clusters are multi tenant, used by 50+ teams (separated by namespaces). As mentioned before, we aim for making everything self-service, this includes configuring cluster wide/shared infra (guarded by a git + PR reviewal process).

# Problem
We use prometheus heavily in our company which makes this project a perfect choice for autoscaling. Our problem (with most of k8s "add-ons") is that the project isn't built for multi tenancy/ decentralised config. This single config works in the beginning but as more and more teams use the service, the config becomes unruly and we have to go through (once again) refactor/cleanup sessions.

# Goal
We want to have config which is generic enough to fit 80% of use cases
We would like to manage config per namespace/decentralised (CRD?)
Potentially driving the prometheus adapter config from the hpa?

# What we are thinking

Write configuration which can be fairly generic regarding standard operations/function application. This wouldn't solve the centralisation but would reduce the amount of times we have to modify the config.
Team wants to use `http_server_requests_seconds_count` from prometheus with a sum and rate function applied with a 5m sample window. They would reference `http_server_requests_seconds_count:rate:5m`. Is this correct?
```
  rules:
    custom:
    - seriesQuery: '{__name__=~"^.*", hpa_custom_metrics!=""}'
      resources:
        template: "<<.Resource>>"
      name:
        matches: "^(.*)"
        as: "$1:rate5m"
      metricsQuery: 'sum(rate(<<.Series>>[5m])) by (<<.GroupBy>>)'
```

Happy to discuss more regarding this!
