### ISSUE TITLE
Count or Sum does not seem to work

### ISSUE THREAD

**Issue by NosIreland** [kubernetes-sigs/prometheus-adapter#568]
**What happened?**:
using `sum` or `count` does not work with metricsQuery. Instead fo getting one item getting multiple
**What did you expect to happen?**:
Expecting to get a single summed item

Here is my rule:
```
    rules:
    - seriesQuery: '{__name__="kube_pod_status_ready"}'
      resources:
        template: "<<.Resource>>"
      name:
        as: "test"
      metricsQuery: 'sum(kube_pod_status_ready{pod=~"metrics-server.*",condition="true"})by(<<.GroupBy>>)'
```
Since there are 2 pods running I expect to get single item with value 2 but here is waht I get:
```
# kubectl get --raw /apis/custom.metrics.k8s.io/v1beta2/namespaces/kube-system/pods/*/test | jq
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta2",
  "metadata": {},
  "items": [
    {
      "describedObject": {
        "kind": "Pod",
        "namespace": "kube-system",
        "name": "metrics-server-8655f897d8-6n5pc",
        "apiVersion": "/v1"
      },
      "metric": {
        "name": "test",
        "selector": null
      },
      "timestamp": "2023-02-28T19:52:01Z",
      "value": "1"
    },
    {
      "describedObject": {
        "kind": "Pod",
        "namespace": "kube-system",
        "name": "metrics-server-8655f897d8-97xsh",
        "apiVersion": "/v1"
      },
      "metric": {
        "name": "test",
        "selector": null
      },
      "timestamp": "2023-02-28T19:52:01Z",
      "value": "1"
    }
  ]
}

```
It ia like `sum` is not used at all. The query works fine in prometheus. Am I missing something?
Thanks

**Comment by TrancalyT** [comment]
@olivierlemasle Do you fix it ? Got the same issue

**Comment by TrancalyT** [comment]
I solve the problme in my case :

This is my rule :
`    - seriesQuery: 'rabbitmq_queue_messages_ready{queue=~"my_queue"}'
      resources:
        overrides:
          namespace: {resource: 'namespace'}
          pod: {resource: 'pod'}
      name:
        as: 'rabbitmq_queue_messages_modules'
      metricsQuery: sum(rabbitmq_queue_messages_ready{queue=~"my_queue"}) by (<<.GroupBy>>)`
      
 Here the output of :` kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" | jq `
![image](https://github.com/kubernetes-sigs/prometheus-adapter/assets/78374998/7a924b8e-f5ae-4efe-9547-ed415a0bd707)

My outuput suggest 2 resources type, so i try to request namespace instead of pods : 
`kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/*/metrics/rabbitmq_queue_messages_modules" | jq`

And bingo got the desired result : 
![image](https://github.com/kubernetes-sigs/prometheus-adapter/assets/78374998/7048b091-b66a-43ac-8697-ecf480bb77d1)

I just have to update my HPA with these lines : 
```
    object:
      metric:
        name: rabbitmq_queue_messages_modules
      describedObject:
        kind: Namespace
        name: care-app
      target:
        type: Value
        value: 50
```
