### ISSUE TITLE
Accessing metric labels in name.as

### ISSUE THREAD

**Issue by sam701** [kubernetes-sigs/prometheus-adapter#578]
I have a few prometheus metrics `queue_length{queue_name="xyz"}` that I want to map to external metrics. I would like to be able to do something like this:
```yaml
- seriesQuery: queue_length
  mericsQuery: max(queue_length) by (queue_name)
  name:
    matches: ""
    as: '<<index .LabelValuesByName "queue_name">>_queue_length'
```
but unfortunately the `as` part does not support templates and the resulting metric name contains `<<index...`.

In order to fix this I have to change the original prometheus metric name to be `xyz_queue_length`. The downside is:
* I have to map each queue name explicitly and
* it is not convenient for dashboards, etc.

It would be great to have support for templates in the `name.as` part or some other mean to access metric labels.
