### ISSUE TITLE
unable to update list of all available metrics 

### ISSUE THREAD

**Issue by mt3593** [kubernetes-sigs/prometheus-adapter#58]
Hi @DirectXMan12 

First off thanks for taking the time to write this library, it's exactly what kubernetes needs. 

I'm not sure the best way of contacting you or someone who can help, I hope it's alright to raise an issue here. This might not be an issue and could just be me not setting up the adaptor properly. I'm pretty new to the rbac and cert setup stuff so had to digest allot of docs to understand these. 

What I am seeing in the adapter logs is this: 
```
I0417 06:59:51.313272       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1: (311.405µs) 404 [[kubectl/v1.6.4 (linux/amd64) kubernetes/d6f4332] 10.211.156.1:58882]
I0417 06:59:51.330025       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1: (273.369µs) 404 [[kubectl/v1.6.4 (linux/amd64) kubernetes/d6f4332] 10.211.156.1:58882]
I0417 06:59:51.341397       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1: (303.466µs) 404 [[kubectl/v1.6.4 (linux/amd64) kubernetes/d6f4332] 10.211.156.1:58882]
I0417 06:59:51.519083       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1: (298.069µs) 404 [[kubectl/v1.6.4 (linux/amd64) kubernetes/d6f4332] 10.211.156.1:58882]
I0417 06:59:51.594021       1 authorization.go:58] Forbidden: "/", Reason: "No policy matched.\nUnknown user \"system:anonymous\""
I0417 06:59:51.594180       1 wrap.go:42] GET /: (3.108636ms) 403 [[Go-http-client/2.0] 10.211.0.5:51826]
E0417 06:59:53.043166       1 provider.go:298] unable to update list of all available metrics: Get http://prometheus-prometheus-server:9090/api/v1/series?match%5B%5D=%7B__name__%3D~%22%5Econtainer_.%2A%22%2Ccontainer_name%21%3D%22POD%22%2Cnamespace%21%3D%22%22%2Cpod_name%21%3D%22%22%7D&amp;match%5B%5D=%7Bnamespace%21%3D%22%22%2C__name__%21~%22%5Econtainer_.%2A%22%7D&amp;start=1523948303.042: dial tcp 10.211.254.128:9090: i/o timeout
```

Now we do have allot of metrics and if I make that call locally it does take a while for all the data to come back. So I think that could be the i/o timeout, to check this is there anyway I can set it up to just get the metrics I'm interested in? 

Also I'm gathering the 404 i'm seeing are due to the fact I cant generate the list of all available metrics?  

The setup I have is this:
 - prometheus is setup via the [helm package](https://github.com/kubernetes/charts/tree/master/stable/prometheus)
<details> 
<summary> - adapter is setup like this </summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-kubernetes-adapter 
  namespace: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-kubernetes-adapter
  template:
    metadata:
      labels:
        app: prometheus-kubernetes-adapter
    spec:
      serviceAccountName: prometheus-kubernetes-adapter
      containers:
      - image: directxman12/k8s-prometheus-adapter:v0.1.0-centos
        name: cm-adapter
        args:
        - --secure-port=6443
        - --logtostderr=true
        # use your serving certs
        - --tls-cert-file=/var/run/serving-certs/tls.crt
        - --tls-private-key-file=/var/run/serving-certs/tls.key
        # Prometheus is running in the same pod, so you can say your Prometheus
        # is at `localhost`
        - --prometheus-url=http://prometheus-prometheus-server:9090
        # relist available Prometheus metrics every 1m
        - --metrics-relist-interval=1m
        # calculate rates for cumulative metrics over 30s periods.  This should be *at least*
        # as much as your collection interval for Prometheus.
        - --rate-interval=30s
        # re-discover new available resource names every 10m.  You probably
        # won't need to have this be particularly often, but if you add
        # additional addons to your cluster, the adapter will discover there
        # existance at this interval
        - --discovery-interval=10m
        - --v=4
        ports:
        # this port exposes the custom metrics API
        - containerPort: 6443
          name: https
          protocol: TCP
        volumeMounts:
        - mountPath: /var/run/serving-certs
          name: serving-certs
          readOnly: true
      volumes:
      - name: serving-certs
        secret:
          secretName: serving-cm-adapter
```

</details>

 - try'ed running ```bash kubectl create clusterrole resource-lister --verb=list --resource="*" ``` but ended up getting ```bash the server doesn't have a resource type "*" ``` which is a bit odd. So just for now I have used a known `clusterrole` with enough privileges and set the rolebinding to that.

<details>
<summary>The apiservice is looking fine from what I can see</summary>

```bash 
kubectl describe apiservice v1beta1.custom.metrics.k8s.io 
Name:         v1beta1.custom.metrics.k8s.io
Namespace:    
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"apiregistration.k8s.io/v1beta1","kind":"APIService","metadata":{"annotations":{},"name":"v1beta1.custom.metrics.k8s.io","namespace":""},...
API Version:  apiregistration.k8s.io/v1beta1
Kind:         APIService
Metadata:
  Creation Timestamp:  2018-04-14T08:58:57Z
  Resource Version:    80344405
  Self Link:           /apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.custom.metrics.k8s.io
  UID:                 10a8278f-3fc2-11e8-a5b7-42010af00031
Spec:
  Ca Bundle:               <shh it's a secret>
  Group:                   custom.metrics.k8s.io
  Group Priority Minimum:  1000
  Service:
    Name:            prometheus-kubernetes-adapter
    Namespace:       metrics
  Version:           v1beta1
  Version Priority:  10
Status:
  Conditions:
    Last Transition Time:  2018-04-16T19:47:23Z
    Message:               all checks passed
    Reason:                Passed
    Status:                True
    Type:                  Available
Events:                    <none>
```
</details>

Any help would be greatly appreciated, I really want to see this adaptor in action :+1: 

Thanks,

Mark
